dialect/sql/graph.go, dialect/sql/graph_test.go
Currently, only fields and own-FKs.
Next PR will add the rest of edge types: M2M, O2M and O2O (non-inverse).
=> dialect/sql/sqlgraph: update nodes using predicate

doc/md/predicates.md
Just doc fixes, no code changes.
=> fix predicates doc type error

doc/md/schema-edges.md
Fix some comment error in schema-edges.md.
=> Fix comment error

doc/md/schema-edges.md
- Comment errors still in schema-edges.md, so.....forgive me for multiple commits.
=> fix comment error in schema-edges.md

schema/field/field_test.go
=> Enhance patch/test cases

dialect/sql/builder.go, dialect/sql/builder_test.go, dialect/sql/schema/migrate.go, dialect/sql/schema/mysql.go, dialect/sql/schema/postgres.go, dialect/sql/schema/postgres_test.go, dialect/sql/schema/sqlite.go, entc/integration/migrate/entv1/example_test.go, entc/integration/migrate/entv1/migrate/schema.go, entc/integration/migrate/entv1/schema/user.go, entc/integration/migrate/entv1/user.go, entc/integration/migrate/entv1/user/user.go, entc/integration/migrate/entv1/user/where.go, entc/integration/migrate/entv1/user_create.go, entc/integration/migrate/entv1/user_update.go, entc/integration/migrate/entv2/example_test.go, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/schema/user.go, entc/integration/migrate/entv2/user.go, entc/integration/migrate/entv2/user/user.go, entc/integration/migrate/entv2/user/where.go, entc/integration/migrate/entv2/user_create.go, entc/integration/migrate/entv2/user_update.go, entc/integration/migrate/migrate_test.go
=> dialect/sql/schema: drop unique constraint on pg migration

entc/integration/template/ent/node.go, entc/integration/template/ent/template/node.tmpl
Signed-off-by: Alex Snast <alexsn@fb.com>
=> entc/gen: fix node out of bounds check

entc/gen/type.go, entc/gen/type_test.go
=> entc/gen: reject fields without name

dialect/sql/schema/mysql.go, entc/integration/ent/example_test.go, entc/integration/ent/fieldtype.go, entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype/where.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/schema/fieldtype.go
=> dialect/sql/schema: correctly read uint32 type in migration

schema/field/field.go
=> fix error description in MaxLen

dialect/sql/builder.go, dialect/sql/builder_test.go
=> dialect/sql: add rename-index to mysql builder

dialect/sql/builder.go, dialect/sql/builder_test.go
=> dialect/sql: add drop/add-index for older version of mysql

entc/gen/func.go
Signed-off-by: Alex Snast <alexsn@fb.com>
=> entc/gen: adding dict implementation to template engine

entc/gen/func.go
Signed-off-by: Alex Snast <alexsn@fb.com>
=> entc/gen: adding list func to template engine

entc/integration/migrate/entv2/user.go
=> regenerate  entc/integration/migrate/entv2/user.go

dialect/sql/schema/migrate.go, dialect/sql/schema/mysql.go, dialect/sql/schema/mysql_test.go
In MySQL (< 8.0), if the table was empty and the server was restarted (e.g. version upgrade), the auto_increment counter will be reset, since it's stored in main memory and not persistent.
=> dialect/sql/schema: verify and fix mysql auto-increment on reset

.circleci/config.yml
Following the discussion in #328, upgrading MySQL8 version.
=> ci: upgrade to mysql latest in integration

entc/gen/type.go, entc/integration/ent/fieldtype.go, entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype/where.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype/where.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go
=> entc/gen: fix nulltype field name for float32

doc/md/hooks.md, doc/website/package.json, doc/website/sidebars.json
=> doc: add hooks documentation and example

cmd/entc/entc.go, cmd/entc/entc_test.go, cmd/entc/packages.go, cmd/entc/packages_test.go, cmd/entc/print.go, cmd/entc/print_test.go, doc/md/code-gen.md, doc/md/getting-started.md
=> cmd/entc: add generate.go file to env init

entc/gen/type.go, entc/gen/type_test.go
=> entc/gen: add schema checks for types

entc/entc.go
=> entc: validate package identifier before running codegen

doc/md/templates.md, doc/website/sidebars.json
=> doc: add a section on external templates

doc/md/sql-integration.md
Add an extra section in doc for pgx with PostgreSQL according to the code provided by @a8m in https://github.com/facebookincubator/ent/issues/563.
=> doc: add a sql.DB integration section for pgx with PostgreSQL

schema/field/field.go, schema/field/field_test.go
resolves - https://github.com/facebookincubator/ent/issues/578
=> schema/field: add the Unique option to the UUID field builder

README.md
ent is not experimental anymore
=> doc: update project status

dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go
This is the first part for adding batch insert support for the framework.
The second part if the codegen.
=> dialect/sql/sqlgraph: initial work for batch insert

entc/gen/type.go, entc/integration/customid/ent/migrate/schema.go, entc/integration/customid/ent/schema/blob.go
=> entc/gen: allow setting unique fields with default values of type function

dialect/sql/sqlgraph/graph.go, entc/integration/customid/ent/migrate/schema.go, entc/integration/customid/ent/schema/user.go, entc/integration/customid/ent/user/user.go
=> dialect/sql/sqlgraph: use correct column when querying m2o/o2o edges

doc/md/code-gen.md, doc/md/schema-edges.md, doc/md/schema-fields.md, doc/md/templates.md, doc/website/siteConfig.js
And add gotemplate to highlight.js as a custom language
=> doc: add schema and template annotations

dialect/sql/builder.go, dialect/sql/builder_test.go, dialect/sql/schema/mysql.go, dialect/sql/schema/mysql_test.go, dialect/sql/schema/postgres.go, dialect/sql/schema/sqlite.go, dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go, entc/integration/config/config_test.go
Add parentheses only when it's necessary.
=> dialect/sql: change boolean operators wrapping

entc/gen/type.go, entc/integration/ent/file.go, entc/integration/ent/file/file.go, entc/integration/ent/file/where.go, entc/integration/ent/file_create.go, entc/integration/ent/file_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/schema/file.go, entc/integration/gremlin/ent/file.go, entc/integration/gremlin/ent/file/file.go, entc/integration/gremlin/ent/file/where.go, entc/integration/gremlin/ent/file_create.go, entc/integration/gremlin/ent/file_update.go, entc/integration/gremlin/ent/mutation.go
=> entc/gen: fix naming conflict for builder fields

dialect/sql/driver.go
Exporting Conn allows users to implement dialect.Driver given *sql.Conn / *sql.Tx.
=> dialect/sql: export conn type

dialect/sql/scan.go, dialect/sql/scan_test.go, entc/integration/customid/customid_test.go
=> dialect/sqlscan: support scanning []uint8 type

doc/md/graphql.md
=> doc/graphql: add more info regarding fields-collections

dialect/sql/builder.go, dialect/sql/builder_test.go
- sql.Selector LeftJoin
- sql.Selector RightJoin
- sql.Selector join
- sql.Selector Ons
- sql.EQCol
- sql.NEQCol
- sql.join Struct
- sql.Selector Join
- sql.Selector Clone
- sql.Selector Query
- sql.join
=> add: dialect sql.Selector LeftJoin

doc/md/schema-fields.md
Add rune length validator example in doc for https://github.com/facebook/ent/issues/784.
=> doc: add rune length validator example

entc/gen/graph.go, entc/gen/graph_test.go, entc/gen/type.go
=> entc/gen: reject codegen in case of duplicate edges

doc/md/faq.md
=> doc: add the audit-logger example for faq page

dialect/sql/builder.go, dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go
=> dialect/sql/sqlgraph: avoid query on update when it's not needed

.github/workflows/ci.yml, entc/integration/compose/docker-compose.yaml, entc/integration/customid/customid_test.go, entc/integration/integration_test.go, entc/integration/json/json_test.go, entc/integration/migrate/migrate_test.go
=> Adding postgres 13

doc/md/faq.md
Requested here: https://github.com/facebook/ent/issues/963#issuecomment-731715046
But for this example to work we need to do `go get github.com/facebook/ent@c1de826324c57262c6477c51520f8effb0a925fc`
=> Added "inet" example in faq

doc/.gitignore, doc/md/getting-started.md
updated docs. Verified in localhost
=> doc: minor change in getting-started and gitignore update

cmd/internal/base/base.go
There was a comment that was bugging me. 😄
=> cmd/ent: fix invalid comment

dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go
This PR adds schema options to all graph operations
=> Add schema options for sql graph

schema/field/field.go, schema/field/field_test.go, schema/field/internal/numeric.tmpl, schema/field/numeric.go
First commit for issue: https://github.com/facebook/ent/issues/944
=> schema/field: add Comment value to Descriptor

doc/md/eager-load.md, doc/md/getting-started.md, doc/md/privacy.md, doc/md/schema-edges.md, doc/md/schema-fields.md, doc/md/schema-indexes.md, doc/md/traversals.md, doc/website/pages/en/index.js
This is a temporary change and will be reverted after the website will be migrated to its new place
=> doc/website: use s3 uri before migrating website

doc/md/getting-started.md
Logs the created Tesla to match the surrounding Getting Started examples.
=> Getting Started: log created Tesla

README.md, README_zh.md
Go language is becoming more and more popular in China. ent is a very powerful framework, and many Chinese people will learn various Go language frameworks。
=> About the language problem of README.md 

dialect/sql/builder.go, dialect/sql/builder_test.go
Allow wrapping placeholder parameters with custom format.
For example, '?' => 'ST_GeomFromWKB(?)'.
=> dialect/sql: add ParamFormatter interface

CONTRIBUTING.md, README.md, README_zh.md
Remove any additional trailing whitespaces from markdown files.
=> Remove whitespace from markdown files

doc/md/graphql.md, doc/md/tutorial-setup.md, doc/md/tutorial-todo-crud.md, doc/md/tutorial-todo-gql-field-collection.md, doc/md/tutorial-todo-gql-node.md, doc/md/tutorial-todo-gql-paginate.md, doc/md/tutorial-todo-gql-tx-mutation.md, doc/md/tutorial-todo-gql.md, doc/website/sidebars.json, doc/website/siteConfig.js
You can review it [here](https://github.com/ent/ent/blob/tutorial/gql/doc/md/tutorial-todo-gql.md) or pull this branch and run `npm start` from `doc/website` branch.
=> tutorial: finish the first graphql tutorial 

dialect/sql/schema/migrate.go, dialect/sql/schema/schema.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/pet/pet.go, entc/integration/ent/schema/pet.go, entc/integration/ent/user/user.go
Fix PostgreSQL index migration when table_name = type_name.
Closed #1344
=> dialect/sql/schema: fix postgres index migration

dialect/sql/builder.go, dialect/sql/builder_test.go
this adds basic predicate helpers do compare 2 columns without having to build them yourself every time.
=> add helpers for basic predicates for comparing 2 columns.

dialect/sql/sqlgraph/entql.go, entc/integration/entql_test.go
=> dialect/sql/sqlgraph: fix incorrect arg-list handling in entql

doc/website/blog/2021-03-18-generating-a-grpc-server-with-ent.md
=> doc/website/blog: fix image url

.github/workflows/ci.yml, dialect/sql/schema/mysql.go, dialect/sql/schema/mysql_test.go, entc/integration/compose/docker-compose.yaml, entc/integration/ent/entql.go, entc/integration/ent/fieldtype.go, entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype/where.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype/where.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/mutation.go, entc/integration/integration_test.go
See https://github.com/ent/ent/issues/1395\#issuecomment-809420881
Fixed #1395
=> dialect/sql/schema: json column migration for mariadb10.3.13

doc/website/docusaurus.config.js
=> doc/website: add locale dropdown menu to navbar

.github/workflows/cd.yml
Every day at 9:00 AM UTC (12PM in Jerusalem).
=> .github/cd: daily pushes for entgo.io website

dialect/sql/builder.go
```
benchmark                                      old ns/op     new ns/op     delta
BenchmarkInsertBuilder_Default/sqlite3-16      285           253           -11.06%
BenchmarkInsertBuilder_Default/mysql-16        283           219           -22.70%
BenchmarkInsertBuilder_Default/postgres-16     374           340           -9.17%
BenchmarkInsertBuilder_Small/sqlite3-16        1945          1734          -10.85%
BenchmarkInsertBuilder_Small/mysql-16          1957          1741          -11.04%
BenchmarkInsertBuilder_Small/postgres-16       2393          2220          -7.23%
benchmark                                      old allocs     new allocs     delta
BenchmarkInsertBuilder_Default/sqlite3-16      5              6              +20.00%
BenchmarkInsertBuilder_Default/mysql-16        5 …
```
=> dialect/sql/sqlbuild: replace bytes.buffer with strings.builder

schema/field/field.go, schema/field/field_test.go
UUID should support nillable to prevent write zero uuid in table, fix #1485
=> field.UUID support Nillable

schema/field/field.go, schema/field/type.go
Fixed https://github.com/ent/ent/issues/1507
=> schema/field: use reflect string for rtype identifier

dialect/sql/builder.go, dialect/sql/builder_test.go
=> sql.Builder Join include Querier's error

doc/md/schema-indexes.md
=> docs/md: add index edge fields example to docs

README.md, README_jp.md
I've added a Japanese version of the README.
=> Add a Japanese version of README.md

.github/ISSUE_TEMPLATE/1.bug.md, .github/ISSUE_TEMPLATE/2.feature.md, README.md, README_jp.md, README_zh.md, examples/README.md
This reduces an unneeded redirect.
=> docs: change `github.com/facebook/ent` to `github.com/ent/ent`

entc/gen/type.go
Until we add the immutable option for edges
=> entc/gen: disallow immutable edge-fields

dialect/sql/schema/mysql.go, dialect/sql/schema/sqlite.go, entc/integration/ent/entql.go, entc/integration/ent/fieldtype.go, entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype/where.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype/where.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/mutation.go, entc/integration/gremlin/ent/runtime.go
=> sql/schema: support custom char type for field.Other

doc/md/graphql.md, doc/md/tutorial-todo-gql.md
- fix broken link
- reorder tutorial command
=> doc/md: fix GraphQL tutorial

doc/md/code-gen.md
=> doc/md: update codegen introduction page

entc/gen/graph.go, entc/integration/edgefield/ent/migrate/schema.go, entc/integration/edgefield/ent/mutation.go, entc/integration/edgefield/ent/schema/user.go, entc/integration/edgefield/ent/user_create.go
=> entc/gen: pass referenced columns schema-type to fk columns

entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/runtime.go, schema/field/field.go, schema/field/field_test.go
=> schema/field: support validator for Bytes fields

entc/gen/type.go, entc/integration/edgefield/ent/car.go, entc/integration/edgefield/ent/car/car.go, entc/integration/edgefield/ent/car/where.go, entc/integration/edgefield/ent/car_create.go, entc/integration/edgefield/ent/car_delete.go, entc/integration/edgefield/ent/car_query.go, entc/integration/edgefield/ent/car_update.go, entc/integration/edgefield/ent/client.go, entc/integration/edgefield/ent/metadata.go, entc/integration/edgefield/ent/metadata/metadata.go, entc/integration/edgefield/ent/metadata/where.go, entc/integration/edgefield/ent/metadata_create.go, entc/integration/edgefield/ent/metadata_query.go, entc/integration/edgefield/ent/metadata_update.go, entc/integration/edgefield/ent/migrate/schema.go, entc/integration/edgefield/ent/mutation.go, entc/integration/edgefield/ent/rental.go, entc/integration/edgefield/ent/rental/rental.go, entc/integration/edgefield/ent/rental/where.go, entc/integration/edgefield/ent/rental_create.go, entc/integration/edgefield/ent/rental_query.go, entc/integration/edgefield/ent/rental_update.go, entc/integration/edgefield/ent/runtime.go, entc/integration/edgefield/ent/schema/car.go, entc/integration/edgefield/ent/schema/metadata.go, entc/integration/edgefield/ent/schema/rental.go
Fixed https://github.com/ent/ent/issues/1723
=> entc/gen: add example for uuid edge-field

doc/md/privacy.md
=> doc/md: slight rewording of privacy.md

doc/md/templates.md, entc/gen/graph.go, entc/integration/template/ent/template/helper.tmpl, entc/integration/template/ent/template/node.tmpl
=> entc/gen: add support for helper templates

doc/website/blog/2021-07-22-database-locking-techniques-with-ent.md
=> doc/website/blog: database locking techniques with ent

dialect/sql/builder.go, dialect/sql/builder_test.go
This change allows writing more robust `ON CONFLICT` clauses.
```go
Insert("users").
Columns("id", "name").
Values("1", "Mashraki").
OnConflict(
ConflictColumns("name"),
ResolveWithNewValues(),
UpdateWhere(NEQ("updated_at", 0)),
)
Insert("users").
Columns("id", "name").
Values("1", "Mashraki").
OnConflict(
DoNothing(),
)
Insert("users").
Columns("id", "name").
Values("1", "Mashraki").
OnConflict(
ConflictColumns("id", "name"),
ResolveWithIgnore(),
)
Insert("users").
Columns("id", "name").
Values("1", "Mashraki").
OnConflict(
ConflictConstraint("users_pkey"),
ResolveWith(func (s *UpdateSet) {
s.SetExcluded("name")
s.SetNull("created_at")
})
)
```
=> dialect/sql: move OnConflict clause to functional options

dialect/sql/builder.go, dialect/sql/builder_test.go
Avoid cases like 'SET a = 1, a = 2'.
=> dialect/sql: override column values on Updater.Set

doc/md/crud.md
Signed-off-by: sadmansakib <ssadman8@gmail.com>
=> fix typo on doc/md/crud.md

schema/index/index.go
Comments do not reflect an up-to-date usage of indexes.
I'm new to ent. Let me know if i missed something.
=> update index comments

doc/website/blog/2021-08-12-building-observable-ent-application-with-prometheus.md
Blog post about prometheus hook for Ent
=> doc/website/blog: blog post prometheus hook

doc/md/eager-load.md
The current code sets the limit to 5 twice
=> docs: Removed extra limit

doc/md/schema-fields.md
following this issue: https://github.com/ent/ent/issues/1840
=> doc/schema-fields: make enum example clearer

dialect/sql/schema/sqlite.go
fix: a typo in the error message
=> fix: error message for the missing fk constraints

doc/website/blog/2021-09-01-ent-joins-the-linux-foundation.md
cc @alexsn @cliedeman @giautm @masseelch @tmc @arielitovsky @ivanvanderbyl @marwan-at-work @rubensayshi @wenerme @tarrencev @mattn @yonidavidson
=> website/blog: ent joins the linux foundation

entc/integration/README.md, entc/integration/compose/gremlin-server/Dockerfile
=> entc/integration: fix gremlin server version

doc/md/extension-api.md, doc/md/extension.md, doc/website/sidebars.js
=> doc/md: initial documentation for the extension API

doc/md/schema-fields.md
Update MaxRuneCount example with entsql.Annotation. 
https://github.com/ent/ent/issues/1637
https://github.com/ent/ent/issues/1856
https://github.com/ent/ent/issues/1914
=> doc/md: update MaxRuneCount example

doc/website/package.json, doc/website/yarn.lock
=> docs/website: upgrade axios resolved version

doc/md/tutorial-todo-gql.md
NewSchema caused an unresolved reference error when I was proceeding with the tutorial. This change was necessary to run the application.
ref: https://github.com/a8m/ent-graphql-example/blob/master/cmd/todo/main.go#L38
=> docs/md: fix unresolved reference

dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go
In PostgreSQL, every statement is executed within a transaction. Therefore, we can avoid
creating transaction blocks manually (group of statements surrounded by BEGIN and COMMIT)
for UpdateNodes operation with a single UPDATE statement.
Benchmark for 2000 operations was improved from:
7.98s      3992160 ns/op    4887 B/op    116 allocs/op
To:
4.42s      2209659 ns/op    4435 B/op    104 allocs/op
---
MySQL and SQLite share the same behavior. Please see #1858 for more info.
=> dialect/sql/sqlgraph: avoid creating tx blocks for single UPDATE statements

doc/website/blog/2021-09-10-openapi-generator.md, doc/website/package.json
=> doc/website/blog: openapi generator

doc/md/schema-edges.md
https://github.com/ent/ent/issues/1061 seems to be a common question ( also see [Slack](https://gophers.slack.com/archives/C01FMSQDT53/p1630519196046300), so link to it in the docs.
=> Link to non-foreign-key join-table fields GH issue

dialect/sql/builder.go, dialect/sql/builder_test.go, dialect/sql/sqlgraph/graph_test.go, entc/gen/template/dialect/sql/feature/upsert.tmpl, entc/integration/ent/card_create.go, entc/integration/ent/comment_create.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/file_create.go, entc/integration/ent/group_create.go, entc/integration/ent/groupinfo_create.go, entc/integration/ent/node_create.go, entc/integration/ent/pet_create.go, entc/integration/ent/task_create.go, entc/integration/ent/user_create.go, entc/integration/integration_test.go
Fixed https://github.com/ent/ent/issues/1952.
cc @tarrencev
=> entc/gen: support de/incrementing values on upsert

.golangci.yml, dialect/sql/schema/mysql.go, dialect/sql/schema/mysql_test.go, entc/gen/func.go, entc/gen/type.go, entc/gen/type_test.go, entc/integration/docker-compose.yaml, entc/integration/ent/migrate/schema.go, entc/integration/ent/schema/user.go, entc/integration/ent/user/user.go, entc/integration/gremlin/ent/user/user.go
Fixed https://github.com/ent/ent/issues/1960
cc @theterminalguy
=> entc/gen: allow spaces in enum fields

entc/integration/ent/entql.go, entc/integration/ent/fieldtype.go, entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype/where.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype/where.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/mutation.go, entc/integration/gremlin/ent/runtime.go, schema/field/field.go
I have a use case where I want to store bytes but I want to use the sensitive option.
=> Add Sensitive() option to bytesBuilder

dialect/sql/schema/migrate.go, dialect/sql/schema/postgres_test.go, entc/integration/ent/entql.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/pet.go, entc/integration/ent/pet/pet.go, entc/integration/ent/pet/where.go, entc/integration/ent/pet_create.go, entc/integration/ent/pet_update.go, entc/integration/ent/schema/pet.go, entc/integration/gremlin/ent/mutation.go, entc/integration/gremlin/ent/pet.go, entc/integration/gremlin/ent/pet/pet.go, entc/integration/gremlin/ent/pet/where.go, entc/integration/gremlin/ent/pet_create.go, entc/integration/gremlin/ent/pet_update.go
This will allow moving from:
field.String(c).Unique()
To:
index.Field(c).Unique()
And vice versa
=> dialect/sql/schema: make Field.Unique and Index.Unique equal

dialect/sql/schema/postgres.go
=> postgres dialect should support other data type like tstzrange and interval

doc/website/blog/2021-11-1-sync-to-external-data-systems-using-hooks.md
cc @masseelch, @giautm, @rotemtam, @yonidavidson, @hilakashai, @hedwigz
=> website/blog: sync objects in external databases

dialect/sql/schema/mysql.go, dialect/sql/schema/mysql_test.go, entc/integration/ent/entql.go, entc/integration/ent/fieldtype.go, entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype/where.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype/where.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/mutation.go, entc/integration/gremlin/ent/runtime.go
Fixed https://github.com/ent/ent/issues/2113
=> dialect/sql/schema: support mediumtext field in migration

entc/gen/template/dialect/sql/create.tmpl, entc/integration/customid/ent/blob_create.go, entc/integration/customid/ent/device_create.go, entc/integration/customid/ent/doc_create.go, entc/integration/customid/ent/mixinid_create.go, entc/integration/customid/ent/note_create.go, entc/integration/customid/ent/pet_create.go, entc/integration/customid/ent/session_create.go, entc/integration/edgefield/ent/car_create.go, entc/integration/ent/item_create.go
Fixed https://github.com/ent/ent/issues/2116
=> entc/gen: allow scanning nil valuescanner types directly from database

dialect/sql/sqljson/sqljson.go, dialect/sql/sqljson/sqljson_test.go, entc/integration/json/json_test.go
Fixed https://github.com/ent/ent/issues/1999
=> dialect/sql/sqljson: support comparing values with null literals

dialect/sql/builder.go, dialect/sql/builder_test.go, entc/integration/integration_test.go
Fixed https://github.com/ent/ent/issues/2126
=> dialect/sql: use identifier qualifiers for WHERE clause on upsert

doc/website/blog/2021-11-10-announcing-entoas.md, doc/website/blog/2021-11-15-announcing-entoas.md
=> doc/website/blog: entoas blog post

dialect/sql/sqljson/sqljson.go, dialect/sql/sqljson/sqljson_test.go, entc/integration/json/json_test.go
Support basic pattern matching in JSON string values
=> dialect/sql: add pattern matching predicates for json values

doc/website/blog/2021-11-15-announcing-entoas.md
=> doc/website/blog: adding code screenshot to entoas blogpost

entc/gen/template/builder/mutation.tmpl, entc/gen/template/builder/setter.tmpl, entc/gen/type.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/mutation.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/mutation.go, entc/integration/hooks/ent/mutation.go, entc/integration/hooks/ent/user_update.go, entc/integration/migrate/entv1/conversion_update.go, entc/integration/migrate/entv1/mutation.go, entc/integration/privacy/ent/mutation.go, entc/integration/privacy/ent/user_update.go, entc/integration/type_test.go
Fixed https://github.com/ent/ent/issues/2166
=> entc/gen: add support for subtracting values from unsgined fields

doc/md/faq.md
question: How to change the character set and/or collation of a MySQL table?
Not sure if the slug path is correct.
=> update faq.md, add new question

doc/md/crud.md
=> docs: fix typo

dialect/sql/schema/mysql_test.go, dialect/sql/schema/postgres_test.go, dialect/sql/schema/schema.go
Fixed https://github.com/ent/ent/issues/2185
=> dialect/sql/schema: fix bug when using multiple table CHECK constraints

doc/website/blog/2021-12-09-contributing-my-first-feature-to-ent-grpc-plugin.md, doc/website/blog/title-tbd.md
=> doc/website/blog: add list blogpost

doc/md/schema-indexes.md
related issue: https://github.com/ent/ent/issues/2215
=> docs: add storage key section in schema-indexes page

dialect/sql/schema/sqlite.go
PR for issue [2209](https://github.com/ent/ent/issues/2209)
=> convert column type string to lower case

dialect/sql/builder.go, dialect/sql/builder_test.go
Closed https://github.com/ent/ent/issues/2236
=> dialect/sql: support passing selectors to basic predicates

dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go
For example, in PostgreSQL, every statement is executed within a transaction. Therefore, we can avoid creating transaction
blocks manually (group of statements surrounded by BEGIN and COMMIT) for CreateNode operation with single SQL statement.
Benchmark was improved from:
(4000 BatchInserts)    17.16s      4289178 ns/op  412893 B/op   4913 allocs/op
To:
(4000 BatchInserts)   9.16s      2288807 ns/op  412142 B/op   4899 allocs/op
=> dialect/sql/sqlgraph: avoid creating tx blocks for single statement batch-create operation

entc/integration/ent/fieldtype/fieldtype.go, entc/integration/ent/fieldtype_create.go, entc/integration/ent/fieldtype_update.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/fieldtype.go, entc/integration/gremlin/ent/fieldtype/fieldtype.go, entc/integration/gremlin/ent/fieldtype_create.go, entc/integration/gremlin/ent/fieldtype_update.go, entc/integration/gremlin/ent/runtime.go, entc/integration/type_test.go, schema/field/field.go, schema/field/field_test.go
Closed https://github.com/ent/ent/issues/2277
=> schema/field: add support for type-aware Default and UpdateDefault in time fields

dialect/entsql/annotation.go, dialect/sql/schema/atlas.go, entc/gen/template/migrate/schema.tmpl, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/schema/user.go, go.mod, go.sum
Fixed https://github.com/ent/ent/issues/1631
=> sql: add support for DESC indexes using annotation and atlasgo.io

schema/edge/edge.go
=> fix comment

doc/website/src/css/custom.css
=> doc/website: change footer title color

doc/md/versioned-migrations.md, doc/website/sidebars.js
forgot to update the sidebar ...
=> doc/md: prettier URL for versioned migrations doc part 2

doc/website/blog/2022-02-15-generate-rest-crud-with-ent-and-ogen.md
Fix the blog post so it works for people.
=> doc/website/blog: ogent is using main instead of master

dialect/sql/schema/atlas.go, entc/integration/customid/customid_test.go
Fixed https://github.com/ent/ent/issues/2401
=> dialect/sql/schema: skip creating unique key for primary keys

dialect/sql/schema/postgres.go, entc/integration/migrate/entv2/customtype.go, entc/integration/migrate/entv2/customtype/customtype.go, entc/integration/migrate/entv2/customtype/where.go, entc/integration/migrate/entv2/customtype_create.go, entc/integration/migrate/entv2/customtype_update.go, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/mutation.go, entc/integration/migrate/entv2/schema/customtype.go, entc/integration/migrate/migrate_test.go, go.mod, go.sum
Fixed https://github.com/ent/ent/issues/2454
=> entc/integration/migrate: update atlas and test custom time precision

dialect/sql/schema/migrate.go, dialect/sql/schema/migrate_test.go
This PR must wait until #2521 is merged.
=> dialect/sql/schema: respect sumfile when present and do not operate on checksum mismatch

dialect/sql/scan.go, dialect/sql/sqlgraph/graph.go, dialect/sql/sqlgraph/graph_test.go, entc/integration/hooks/ent/schema/card.go, entc/integration/integration_test.go, entc/integration/privacy/ent/schema/base.go, entc/integration/privacy/privacy_test.go
=> dialect/sql/sqlgraph: better support for update nodes with predicates

entc/gen/type.go, entc/integration/edgeschema/ent/migrate/schema.go, entc/integration/edgeschema/ent/schema/friendship.go, entc/integration/edgeschema/ent/schema/relationship.go
Fixed https://github.com/ent/ent/issues/2575
=> entc/gen: support indexing edge schema with composite primary keys

doc/md/tutorial-todo-crud.md
quick fix to enum valus in the docs
=> doc/md: fixing NamedValues option in Add Fields To The Schema example

entc/integration/json/ent/schema/user.go, entc/integration/json/ent/user.go, entc/integration/json/json_test.go, schema/field/field.go, schema/field/field_test.go
Closed https://github.com/ent/ent/issues/2596
=> schema/field: support for sensitive json fields

dialect/sql/sqlgraph/graph.go, entc/integration/edgeschema/edgeschema_test.go
=> dialect/sql/sqlgraph: handle edge schema in batch inserts

doc/md/transactions.md, doc/md/tutorial-todo-gql-tx-mutation.md
Hey! I've added some docs for tweaking isolation levels.
Talked about this with @a8m on Discord.
=> docs: document tweaking transaction isolation levels

doc/md/dialects.md
=> chore: update dialects doc to reflect postgres 14 testing

doc/md/tutorial-grpc-generating-a-service.md, doc/md/tutorial-grpc-service-generation-options.md
=> doc/md: update grpc tutorial for List and BatchCreate methods

dialect/sql/sqljson/sqljson.go, dialect/sql/sqljson/sqljson_test.go, entc/integration/json/ent/schema/user.go, entc/integration/json/json_test.go
=> dialct/sql/sqljson: fix HasKey implementation for SQLite

dialect/sql/builder.go, dialect/sql/builder_test.go
=> dialect/sql/builder: added FullJoin

dialect/sql/sqljson/sqljson.go
Signed-off-by: Abirdcfly <fp544037857@gmail.com>
=> chore: remove duplicate word in comments

go.mod
Upgrade version in go mod to 1.19
=> Upgrade go version

cmd/internal/printer/printer.go
Fixed https://github.com/ent/ent/issues/2928.
=> cmd/ent: support 'ent describe' in edge-schemas

README_jp.md
* URL fix
* Correct your expressions more fluently
=> doc: minor fix Japanese README

doc/md/tutorial-todo-gql-paginate.md
Please take a look. Same change as for the previous page.
=> doc: make mutation and variable match todo.graphql

doc/md/tutorial-todo-gql-field-collection.md
Please take a look.
(As an aside, I did not get what this page was trying to get across as the code as provided did not generate 11 queries and there is no indication that I could see on the page for how to alter the **disabling fields collection** behaviour).
=> docs: fix file name for required change

doc/md/dialects.md
Closed https://github.com/ent/ent/issues/2997
=> doc: update sqlite migration section

doc/website/blog/2022-10-10-json-append.mdx
=> doc/website/blog: json append blogpost

dialect/sql/scan.go, dialect/sql/scan_test.go, entc/integration/json/ent/schema/user.go, entc/integration/json/ent/user.go, entc/integration/json/json_test.go
Closed https://github.com/ent/ent/issues/3019, https://github.com/ent/ent/issues/2052.
=> dialect/sql: support scanning json fields

entc/gen/graph_test.go, entc/gen/type.go
Fixed https://github.com/ent/ent/issues/2205.
=> entc/gen: ensure edge.StorageKey and edge.Field do not conflict

dialect/entsql/annotation.go, dialect/sql/schema/mysql.go, dialect/sql/schema/postgres.go, entc/gen/template/migrate/schema.tmpl, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/schema/user.go, entc/integration/migrate/migrate_test.go, go.mod, go.sum
Fixed https://github.com/ent/ent/issues/3041.
=> dialect/sql: add support for index operator-class using atlasgo.io

dialect/sql/schema/atlas.go, dialect/sql/schema/mysql.go, dialect/sql/schema/postgres.go, dialect/sql/schema/sqlite.go, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/mutation.go, entc/integration/migrate/entv2/runtime.go, entc/integration/migrate/entv2/schema/user.go, entc/integration/migrate/entv2/user.go, entc/integration/migrate/entv2/user/user.go, entc/integration/migrate/entv2/user/where.go, entc/integration/migrate/entv2/user_create.go, entc/integration/migrate/entv2/user_update.go, entc/integration/migrate/migrate_test.go
Fixed https://github.com/ent/ent/issues/3080
=> dialect/sql/schema: allow setting JSON default values on pg, sqlite and maria

dialect/entsql/annotation.go, dialect/sql/schema/atlas.go, dialect/sql/schema/mysql.go, dialect/sql/schema/schema.go, doc/md/schema-fields.md, entc/gen/func.go, entc/gen/template/migrate/schema.tmpl, entc/gen/type.go, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/mutation.go, entc/integration/migrate/entv2/runtime.go, entc/integration/migrate/entv2/schema/user.go, entc/integration/migrate/entv2/user.go, entc/integration/migrate/entv2/user/user.go, entc/integration/migrate/entv2/user/where.go, entc/integration/migrate/entv2/user_create.go, entc/integration/migrate/entv2/user_update.go, entc/integration/migrate/migrate_test.go
Fixed https://github.com/ent/ent/issues/3069
=> dialect/sql/entsql: support setting expression as column default value

doc/md/getting-started.mdx
Are you sure the MySQL file path name is correct?
If you put it in start.go under the start directory, it would be inconsistent with the sample code.
https://entgo.io/ja/docs/getting-started/#query-your-entities
remove `start/`
```markdown
go title="entdemo/start.go
```
=>  Change the file path listed on the MySQL tab of the "Create First Entity" section

doc/md/versioned/03-auto-plan.md
=> Corrected design deviations in the text.

doc/md/versioned/07-verifying-safety.md
=> fix typo on tutorial

entc/gen/template/ent.tmpl, entc/integration/template/ent/schema/user.go, entc/integration/template/ent/user.go, schema/schema.go
Adds new mechanism for customizing a model's godoc comment in code (via an Annotation). Resolves #3155.
=> Add schema.CommentAnnotation

doc/md/tutorial-todo-gql-mutation-input.md
=> doc/md: create edges with mutation

doc/md/community.md, doc/website/docusaurus.config.js, doc/website/sidebars.js
=> doc/md: update join community page

doc/md/hooks.md, entc/load/load.go, entc/load/load_test.go, entc/load/testdata/cycle/fakent/fakent.go, entc/load/testdata/cycle/schema.go
Fixed https://github.com/ent/ent/issues/3263.
=> entc/load: better error reporting for import cycles

entc/gen/template/meta.tmpl, entc/gen/template/runtime.tmpl, entc/integration/ent/entql.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/node.go, entc/integration/ent/node/node.go, entc/integration/ent/node/where.go, entc/integration/ent/node_create.go, entc/integration/ent/node_update.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/node.go, entc/integration/gremlin/ent/mutation.go, entc/integration/gremlin/ent/node.go, entc/integration/gremlin/ent/node/node.go, entc/integration/gremlin/ent/node/where.go, entc/integration/gremlin/ent/node_create.go, entc/integration/gremlin/ent/node_update.go, entc/integration/gremlin/ent/runtime.go, entc/integration/integration_test.go
This fixes: #3217, nothing much to say.
=> entc/gen: ensure UpdateDefault is generated

doc/md/tutorial-todo-gql.mdx
fixed typo, I am sure it meant where instead of when.
=> docs: Updated fixed a typo

dialect/sql/schema/atlas.go, entc/integration/migrate/migrate_test.go
For https://github.com/ariga/atlas/pull/1454
=> dialect/sql/schema: ensure consistency of NotCleanError

examples/go.mod, examples/go.sum, go.mod, go.sum
For https://github.com/ent/ent/pull/3310
=> go: update ariga.io/atlas

dialect/sql/schema/atlas.go, dialect/sql/schema/schema.go, doc/md/schema-annotations.md, entc/gen/graph.go, entc/gen/template/migrate/schema.tmpl, entc/gen/type.go, entc/integration/migrate/entv2/media.go, entc/integration/migrate/entv2/migrate/schema.go, entc/integration/migrate/entv2/schema/media.go, entc/integration/migrate/migrate_test.go, schema/schema.go
Fixed https://github.com/ent/ent/issues/2271#issuecomment-1453795640.
=> dialect/sql/schema: allow setting table comments

dialect/sql/schema/writer.go, dialect/sql/schema/writer_test.go
Fixed https://github.com/ent/ent/issues/3362.
=> dialect/sql/schema: expand fmt.Stringer args in WriteDriver

entc/integration/json/ent/migrate/schema.go, entc/integration/json/ent/mutation.go, entc/integration/json/ent/schema/user.go, entc/integration/json/ent/user.go, entc/integration/json/ent/user/user.go, entc/integration/json/ent/user/where.go, entc/integration/json/ent/user_create.go, entc/integration/json/ent/user_update.go, entc/integration/json/json_test.go, schema/field/field.go, schema/field/field_test.go
Fixed https://github.com/ent/ent/issues/3104
=> schema/field: allow using JSON fields with type 'any'

README.md, README_kr.md
I want a lot of Koreans to use entgo, so I decided to translate readme file
=> readme : add korean language

dialect/entsql/annotation.go
=> entsql: added OnDelete annotation

doc/md/schema-annotations.md
=> doc/md: update doc for OnDelete annotation

.github/workflows/atlas-ci-public.yaml
=> .github/workflow: added atlas-ci for examples

.github/workflows/atlas-ci-public.yaml
=> .github/workflow: sync action

doc/md/versioned/02-auto-plan.mdx
Fix typo in docs: databaes into database
=> Fix typo in docs

dialect/sql/builder.go
Closed https://github.com/ent/ent/issues/3487.
=> dialect/sql: expose the underlying builder of UpdateSet

entc/gen/template/builder/create.tmpl, entc/gen/template/builder/update.tmpl, entc/integration/ent/entql.go, entc/integration/ent/migrate/schema.go, entc/integration/ent/mutation.go, entc/integration/ent/runtime.go, entc/integration/ent/schema/task.go, entc/integration/ent/task.go, entc/integration/ent/task/task.go, entc/integration/ent/task/where.go, entc/integration/ent/task_create.go, entc/integration/ent/task_update.go, entc/integration/gremlin/ent/mutation.go, entc/integration/gremlin/ent/runtime.go, entc/integration/gremlin/ent/task.go, entc/integration/gremlin/ent/task/task.go, entc/integration/gremlin/ent/task/where.go, entc/integration/gremlin/ent/task_create.go, entc/integration/gremlin/ent/task_update.go
Fixed https://github.com/ent/ent/issues/3548
=> entc/gen: fix conflicts between fields named 'op' and Mutation.Op

ent.go
Fixed https://github.com/ent/ent/issues/3471
=> ent: document ent.Value returned by mutations

doc/website/docusaurus.config.js, doc/website/package.json, doc/website/src/css/custom.css, doc/website/yarn.lock
Surprisingly (not really), this is not that obvious these days.
=> doc/website: we stand with israel; we we israel

entc/gen/feature.go, entc/gen/graph.go, entc/gen/graph_test.go
=> entc/gen: keep internal feature-flags private

dialect/sql/schema/mysql.go
This PR adds support for notive UUID datatype for SQL mariaDB. Since version 10.7.0 the uuid datatype was introduced. It offers better performance than the varchar(36) binary that ent now offers.
The check will make sure mariadb and the correct version is used to allow the UUID datatype. This was tested during creating a migration file.
Als in the dependent project atlas i created a PR that is kinda dependent before this change can be merged
Please check https://github.com/ariga/atlas/pull/1302
=> added support for mariadb uuid native type

entc/gen/graph.go
After #584 goimports does not need to resolve packages, and running concurrent fmt is faster than serialized one
=> entc/gen: concurrent gofmt

doc/md/getting-started.mdx
Removed unneeded boilerplate from several code sections in mdx file. 
The removed sections were confusing as they had some of the file's first few lines (package, imports) but not the full file.
In addition, they were not consistent with other parts of the markdown.
=> Getting Started MDX Improvements

entc/gen/template/builder/query.tmpl, entc/integration/ent/api_query.go, entc/integration/ent/builder_query.go, entc/integration/ent/card_query.go, entc/integration/ent/comment_query.go, entc/integration/ent/exvaluescan_query.go, entc/integration/ent/fieldtype_query.go, entc/integration/ent/file_query.go, entc/integration/ent/filetype_query.go, entc/integration/ent/goods_query.go, entc/integration/ent/group_query.go, entc/integration/ent/groupinfo_query.go, entc/integration/ent/item_query.go, entc/integration/ent/license_query.go, entc/integration/ent/node_query.go, entc/integration/ent/pc_query.go, entc/integration/ent/pet_query.go, entc/integration/ent/spec_query.go, entc/integration/ent/task_query.go, entc/integration/ent/user_query.go, entc/integration/json/ent/user_query.go, entc/integration/multischema/ent/friendship_query.go, entc/integration/multischema/ent/group_query.go, entc/integration/multischema/ent/pet_query.go, entc/integration/multischema/ent/user_query.go, entc/integration/multischema/versioned/friendship_query.go, entc/integration/multischema/versioned/group_query.go, entc/integration/multischema/versioned/pet_query.go, entc/integration/multischema/versioned/user_query.go
Fixed https://github.com/ent/ent/issues/4026
=> entc/gen/template: clone modifiers if enabled

dialect/sql/schema/atlas.go, entc/integration/migrate/migrate_test.go
Since SQLite does not allow enabling/disabling foreign key checks within a transaction, Atlas disabled foreign key checks before opening a transaction and re-enables them after commit/rollback. This involves checking for violations every time the auto migrate tool checks for changing. By opening a transaction only in case there are changes, we can avoid this when not needed.
Closes https://github.com/ariga/atlas/issues/3297
=> dialect/sql/schema: inspect outside transaction in auto migrate

doc/md/faq.md
Revert https://github.com/ent/ent/commit/5c91f752b71a535208c5fbca7bec4e985a575925
It is also already described in the annotations docs
=> doc/faq: revert 5c91f7

entc/gen/globalid.go
=> entc/gen: allow writing increments to disk

dialect/sql/schema/atlas.go, dialect/sql/schema/schema_test.go
https://github.com/ariga/atlas/issues/3307#issuecomment-2703007075
=> dialect/sql/schema: qualify if schema is given

.github/workflows/ci.yml, entc/integration/docker-compose.yaml, entc/integration/integration_test.go
=> entc/integration: add integration testing for PG16 and PG17

cmd/internal/base/base.go, dialect/sql/schema/atlas.go, dialect/sql/schema/schema.go, dialect/sql/schema/schema_test.go
Related: https://github.com/ent/ent/pull/4359
=> dialect/sql/schema: add option to control symbol hashing logic for schema dump
