ent/ent

dialect/sql/builder.go
dialect/sql/builder_test.go

Implements the predicates for composite where queries. It is the first step towards key-set pagination support as discussed in #215

add predicates for composite where query

---

.circleci/config.yml

Following my bug report in MySQL issue tracker,
I've pinned MySQL8 version to be 8.0.18 until
we figure out if it's a bug or a new change that
we need to support.
Link: https://bugs.mysql.com/bug.php?id=98250

ci: pin mysql8 to mysql 8.0.18 (not latest)

---

dialect/sql/builder.go
dialect/sql/builder_test.go

Old versions of MySQL (<8) do not support the 'RENAME' caluse

dialect/sql: add change-column for mysql

---

dialect/sql/driver.go
dialect/sql/schema/migrate.go
dialect/sql/schema/mysql.go
dialect/sql/schema/postgres.go
dialect/sql/schema/sqlite.go

In most cases, the sql.Result is not needed.

dialect/sql: allow nil values for exec commands

---

entc/gen/func.go

Signed-off-by: Alex Snast <alexsn@fb.com>

entc/gen: adding tagLookup / strings.Split functions to template engine

---

entc/gen/graph_test.go

Solve https://github.com/facebookincubator/ent/issues/307
After running go test -v to test the project, the dir ent will be generated in $TMPDIR, I think we should delete the ent after test just in case, or it will affect the test result next time in some unknown cases.

delete TMPDIR/ent generated by go test

---

dialect/sql/sqlgraph/graph.go
go.mod
go.sum

If the underlying driver does not support JSON types, driver.DefaultParameterConverter
will convert it to uint8.

sqlgraph/convert: use json.RawMessage for JSON types

---

dialect/sql/schema/sqlite.go

Until the SQLite migration will be resolved, we need to return a better error message to users than just panic

dialect/sql/schema: better error message for sqlite limitation

---

.golangci.yml
dialect/sql/builder.go
dialect/sql/builder_test.go
dialect/sql/schema/migrate.go
dialect/sql/schema/mysql.go
dialect/sql/schema/mysql_test.go
dialect/sql/schema/postgres.go
dialect/sql/schema/schema.go
dialect/sql/schema/sqlite.go
dialect/sql/schema/sqlite_test.go
entc/integration/migrate/migrate_test.go

This is a modified version of PR #221 created by Erik Hollensbe (@erikh). 
It adds basic functionality like adding fields/edges for schemas, but dropping/modifying columns or constraints is not working at the moment.

dialect/sql/schema: initial work for incremental migration

---

entc/gen/func.go
entc/integration/ent/migrate/schema.go
entc/integration/ent/schema/user.go
entc/integration/ent/user/user.go
entc/integration/gremlin/ent/user/user.go

I've been evaluating Ent for production use and ran into a small issue with the code gen and enums. If an enum string value is `kebab-case` the generated go code isn't valid. For example:
```go
...
field.Enum("role").
Values("user", "admin", "free-user").
Default("user")
...
```
Generates:
```go
...
// Role values.
const (
RoleUser Role = "user"
RoleAdmin Role = "admin"
RoleFree-user Role = "free-user"
)
...
```
The issue is `RoleFree-user` isn't a valid Go variable name.
I've enhanced the Pascal/camelCase string conversion functions to split on `-` as well as `_`. The resulting code gen is more expected:
```go
// Role values.
const (
RoleUser     Role = "user"
RoleAdmin    Role = "admin"
RoleUser     Role = "user"
RoleAdmin    Role = "admin"
RoleFreeUser Role = "free-user"
)
```

Split strings in pascal/camcelCase conversion on - in addition to _

---

entc/gen/graph.go
entc/gen/graph_test.go
entc/load/schema_test.go
schema/edge/edge_test.go

This PR contains one line fix (in `graph.go`), but additional tests to all annotations workflow.

schema/edge: fix edge annotations with to/from builders

---

entc/gen/bench_test.go
entc/gen/graph.go

Calling {{ fail "error" }} from external template should terminate the execution without local changes.

entc/gen: don't write assets on template failures

---

entc/entc.go
entc/gen/graph.go
entc/gen/type.go

derive the id-type from the schema if it was not provided

entc/gen: derive the id-type from the schema

---

entc/gen/type.go

Added `'Client'` in the `globalIdent` list. Fixes #873

Fix naming conflict for 'Client'

---

doc/md/schema-edges.md
examples/README.md
examples/o2mrecur/example_test.go

Looks like `CreateX` was deprecated and this comment is slightly outdated.

doc: replace CreateX reference to SaveX

---

entc/gen/type.go

Resolution for #918. After the comment from @a8m and a bit of poking around, I felt confident in putting this in.

entc/gen: ensure that edges are able to use golang keywords

---

entc/gen/type.go
entc/integration/idtype/ent/migrate/schema.go

fix: pk forces the Type of the numeric to be TypeInt so that the user defined id type is invalid

fix: pk forces the Type of the numeric to be TypeInt so that the user defined id type is invalid

---

dialect/entsql/annotation.go
dialect/sql/schema/mysql.go
dialect/sql/schema/mysql_test.go

resolves #924 
Added `Option` field in the `Annotations` struct so that users can specify additional options like `ENGINE = INNODB` when creating a table

feat: Added Annotation Options

---

dialect/sql/schema/postgres.go

When the table already exists and has column the type is "timestamp without time zone", using migrate will return an error.
```
2020/11/14 05:09:34 failed printing schema changes: sql/schema: invalid type "timestamp without time zone" for column "create_time"
```
This is because when scanning column types, the corresponding ones are not processed.

fix invalid type, add an postgre type 'timestamp without time zone' to the scan colum

---

dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go

dialect/sql/schema: skip default value parsing on pg functions

---

dialect/sql/sqlgraph/graph.go
entc/integration/customid/customid_test.go

dialect/sql/sqlgraph: fix postgres lastinsert scanning for non-integer types

---

dialect/sql/builder.go
dialect/sql/sqlgraph/entql.go
dialect/sql/sqlgraph/graph.go
entc/gen/feature.go
entc/gen/graph.go
entc/gen/type.go
schema/edge/edge.go
schema/index/index.go

I was noticing a few linting errors relating to comments. Personally, I like a warning-free environment so that important warnings don't get lost. There are quite a few more linting problems but I left them alone as they would require changes to function signatures or they are false-negatives and that's outside the scope of this PR.
I also didn't touch any of the integration comments as I'm not sure what's connected to docs and what isn't. 
Happy to review if needed.
<details>
<summary>What's left</summary>
```
dialect\sql\builder.go:2024:2: exported const OpEQ should have comment (or a comment on this block) or be unexported
entc\gen\internal\bindata.go:613:5: var _templateDialectSqlByTmpl should be _templateDialectSQLByTmpl
entc\gen\internal\bindata.go:615:6: func …
```

fix: linting errors for comments

---

dialect/sql/schema/mysql.go
dialect/sql/schema/mysql_test.go

Enums are not longer created as sorted values

dialect/sql/mysql: remove enum sorting

---

entc/load/load.go

packages.LoadSyntax mode is deprecated, replacing with what's needed.

entc: drop deprecated packages.LoadSyntax usage

---

cmd/internal/base/base.go
entc/gen/type.go

Adds in name conflict checking when running `ent init` to provide better feedback to the user when generating new schemas.
Also made error handling more concise for `init` to show what went wrong when
Closes #1109 
New Error: `ent/init: init schema Client: schema name conflicts with ent predeclared identifier "Client"`

entc/init: name conflict checks

---

ent.go

Fixes the indentation of the usage code example under the `Policy` type
so that proper formatting is applied.
Previously had formatting like:
>type T struct {
>```
>ent.Schema
>```
>}
Updates to:
>```
>type T struct {
>    ent.Schema
>}
>```

ent: fix Policy documentation code formatting

---

entc/integration/compose/docker-compose.yaml

This supplies platform: `linux/amd64` in the compose test file. This enables running integration tests on arm64 machines.

entc/integration: specify platform in integration test services

---

dialect/sql/builder.go
dialect/sql/builder_test.go

This PR adds schema options to all the SQL builders (insert, delete, update etc) to pave the way for users to customize the database name for each table. 

Add schema options for sql builders

---

dialect/sql/builder.go
dialect/sql/builder_test.go

SQLite does not have schema prefixes when referencing a table, make sure the Builders account for this case.

Skip schema prefix when dialect is SQLite

---

dialect/sql/schema/mysql.go
dialect/sql/schema/mysql_test.go

In MySQL 8.0 UUID's are handled via binary columns.

dialect/sql/schema: add mysql binary support for native uuid handling

---

dialect/sql/schema/migrate.go
dialect/sql/schema/migrate_test.go

add hooks to Migrate to allow filtering and mutation of the tables being created.
as per https://github.com/facebook/ent/issues/1079 this will make it possible to change or remove tables before they're created for any custom modifications needed.
```go
migrate, err := schema.NewMigrate(sql.OpenDB("mysql", db), schema.Hook(func(next CreateFunc) CreateFunc {
return func(ctx context.Context, tables ...*Table) error {
return next(ctx, tables[0], &Table{Name: "pets"})
}
}))
```

add hooks to Migrate

---

doc/md/schema-annotations.md
doc/md/templates.md

These links were to the Annotation type in schema/field vs the interface in the schema package.

docs: fix link to Annotation interface

---

entc/internal/snapshot.go

A syntax error caused by a conflict marker doesn't get caught by the IsBuildError function, causing Ent not to try and recover using the stored schema snapshot. In this PR we add a check for the substring `found '<<'`.

entc/internal: catch syntax error due to conflict marker

---

dialect/sql/builder.go
dialect/sql/builder_test.go

This PR adds a context to the sql selector so that we can pass values from the generate code which can be extracted later as dynamic configuration for the query builder

Add context.Context to sql.Selector

---

dialect/sql/sqlgraph/graph.go
dialect/sql/sqlgraph/graph_test.go

This PR ensures that sqlgraph functions that receive a context and create a selector will make sure to pass the context to said selector so that future predicate functions can extract data relevant to them. 

Ensure sqlgraph passes the context to *sql.Selector

---

entc/gen/feature.go

Adds the feature flag option to expose alternate schema names (which at this point doesn't do anything yet)

Add sql/schemaconfig feature flag

---

doc/md/graphql.md

This change extends the graphql examples mentioned to point to the Prefixed ULID (`PULID`) approach.

doc/graphql: extend examples section to mention the PULID example

---

doc/md/features.md

Adds instructions on how to provide custom schemas to ent models.

Add documentation for the sql/schemaconfig feature

---

doc/md/code-gen.md
doc/md/getting-started.md
doc/md/privacy.md
doc/md/schema-edges.md
doc/md/schema-indexes.md
doc/md/transactions.md
doc/md/traversals.md
examples/README.md

I was happily reading ent documentation site and found that the link to github was broken
`https://entgo.io/ent/tree/master/examples/ `-> `https://github.com/facebook/ent/tree/master/examples/`

doc: fix github link

---

entc/gen/type.go

Fixes #1225 
Supplementary to #1110 
Adds checks for schema names against private identifiers when running codegen and using `ent init`

entc: add extra name check for private identifiers

---

.golangci.yml

Now that the problematic function has been excluded - https://github.com/facebook/ent/blob/dd4792f5b30bdd2db0d9a593a977a54cb3f0c1ce/entc/integration/ent/schema/fieldtype.go#L31
The funlen can be reduced to its original size

chore: reduce funlen

---

dialect/sql/builder.go
dialect/sql/builder_test.go

Opening this PR to demonstrate something which I think is a bug.  
It also includes a fix, but I can't say with 100% certainty this is the right fix.
I was using the `sql.Expr` to construct some custom query stuff and noticed that there was something wrong with the parameter numbering in postgres.
there's 2 tests to demonstrate the issue, both fail when the `b.total = st.Total()` is left in place.
the problem seems to be that without the `b.total = st.Total()` we loose the previously set `.SetTotal`, but with it it will reset it when we're doing nested predicates.  
I think my fix will work in both cases, and all tests pass ...

[bug] using .Total() in builder.Join results in wrong count

---

dialect/sql/sqlgraph/graph.go
entc/integration/customid/customid_test.go

Fixed #1290. Issue in BulkCreate(<T>) for m2m edges

dialect/sql/sqlgraph: skip setting last-insert-id if provided

---

dialect/sql/bench_test.go
dialect/sql/builder.go

```
benchmark                                     old ns/op     new ns/op     delta
BenchmarkInsertBuilder_Default/default-16     6210          922           -85.15%
benchmark                                     old allocs     new allocs     delta
BenchmarkInsertBuilder_Default/default-16     86             16             -81.40%
benchmark                                     old bytes     new bytes     delta
BenchmarkInsertBuilder_Default/default-16     4098          1088          -73.45%
benchmark                                    old ns/op     new ns/op     delta
BenchmarkInsertBuilder_Small/sqlite3-16      2169          1801          -16.97%
BenchmarkInsertBuilder_Small/mysql-16        2140          1825          -14.72%
BenchmarkInsertBuilder_Small/postgres-16     2613          2223 …
```

dialect/sql: minor improvements to insert command

---

.github/workflows/cd.yml
doc/website/crowdin.yaml
doc/website/docusaurus.config.js
doc/website/package.json
doc/website/src/pages/index.js

Enabling i18n. Currently not adding the language picking to the top navbar until we have some content in. 
Adding crowdin sync to the CD flow. 
Changing `<a>` tags that ref internal document in the index page to `<Link>` components so b/c docusaurus will account for i18n that way. 
Before merging we need to set the Crowdin env var for the auth token.

enable crowdin translation 

---

doc/md/schema-edges.md
entc/gen/graph.go
entc/integration/migrate/entv2/migrate/schema.go
entc/integration/migrate/entv2/schema/media.go
entc/integration/migrate/entv2/schema/user.go
entc/integration/migrate/migrate_test.go
schema/edge/edge.go
schema/edge/edge_test.go

Fixed #1423
I'd be happy to move the edge storage-key configuration to `entsql.Annotation` at some point since it's under the `schema/edge` for legacy reasons. But it can be done in future PRs.

schema/edge: add support for configuring foreign-key symbols

---

dialect/sql/schema/schema.go

A schema definition like:
```
field.Bytes("data"),
```
errors when schema changes are printed with:
```
failed printing schema changes: sql/schema: unsupported default type: []byte
```
This PR addresses this issue.

handle pg bytea for schema changes

---

dialect/sql/builder.go
dialect/sql/builder_test.go

Hello ! 
I recently found a ticket mentioning the performance problem of EqualFold because it used "lower", and the impact it had on the different indexes. (#1484 )
I took some inspiration from the ContainsFold method and updated EqualFold to follow the same pattern, except for SQLite that needed the old way of doing (because if we have to lower on both sides, let's just use equal)

Dialect: improve equalfold

---

doc/md/dialects.md

* MariaDB 10.3 has supported by https://github.com/ent/ent/pull/1407.
* PostgreSQL 13 has supported by https://github.com/ent/ent/pull/961.

doc: update supported dialects

---

dialect/sql/builder.go
dialect/sql/builder_test.go
dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go
dialect/sql/schema/sqlite.go

Append-only mode creates tables with the `IF NOT EXISTS` annotation.
Make indices case symmetric with this.

Add IndexBuilder.IfNotExists and use for Create() case.

---

.golangci.yml
dialect/sql/schema/inspect_test.go
dialect/sql/schema/migrate.go
dialect/sql/schema/mysql.go
dialect/sql/schema/mysql_test.go
dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go

Currently if you have a `field.Float("price").SchemaType(map[string]string{dialect.Postgres: "numeric(6, 4)"})` field then the migration will forever think that it needs to change the type because when scanning the existing table structure it will see it as just `numeric` without the precision and scale.
This PR fixes that by looking at the `numeric_precision` and `numeric_scale` fields which are present in the `information_schema.columns` for both engines.
I chose to use the `c.SchemaType` instead of adding the metadata to the `Column{}` since currently that's also how it's being created anyway.
I suppose in the future we could maybe add a `field.Decimal` field type and use `big.Float` or https://github.com/shopspring/decimal as the GoType for it ... 
I added 2 test cases, one to check …

Add support for postgres and mysql numeric and decimal types in migrations

---

dialect/sql/builder.go
dialect/sql/builder_test.go

Working with ent is a great experience, and I found it also useful in maintaining raw queries and index creation where the static nature of ent can be at least used with existing generated entities.
Most of the custom stuff requires completely new structures (like for `create/drop text search dictionary` or `create/drop text search configuration`), so there was no need for any modification. However with the index creation there is a `USING <method>` portion - at least in Postgres, where `btree`, `hash`, `gist`, `spgist`, `gin`, and `brin` can be specified. Unfortunately this construction hast to be right in front of the column list, so I'm asking if this could be simply added to the ent itself, as creating a completely new batch of methods seems like an overkill. May be in the future this …

Support for USING 'method' in create index

---

dialect/sql/builder.go
dialect/sql/builder_test.go

As reported in issue #1754 , specifying ORDER BY with union results in syntax error as ORDER BY wrongly gets appended before UNION. This PR fixes that by modifying the builder to append UNION before ORDER BY.
- Resolves #1754

Fix: Append UNION before ORDER BY

---

dialect/sql/builder.go

In case selector's from clause has *Selector instead of *SelectTable,
TableName() function (used for column checking) will panic.
Instead, return selector's alias which is useful if the query returns
a table with the same schema as some entity. Essentially, this allows
materialized views to reuse the same entity code as long as columns
are matching.

Return selector's alias as a table name

---

dialect/sql/driver.go

This allows you to use `.Nillable()` on a column with a `.GoType()` which doesn't support `Scan(nil)`.
In our cases this was for `field.Float("price").GoType(decimal.Decimal{}).Nillable()`.  
Now I know there's `decimal.NullDecimal` in this case but it's more cumbersome and the property will actually be a pointer to `decimal.NullDecimal`: `price *decimal.NullDecimal` because of the `Nillable()` (which you want to set the NULL in the migration).  
As a result you get things like `update.SetPrice(&decimal.NullDecimal{Decimal: request.Decimal, Valid: true})` where you need to create a pointer to the struct which is already intended to manage the nullness of the value :/
And I do think this is probably applicable to other things which people would like to use for .GoType()`, not every …

don't call inner Scan for nil values

---

doc/md/writing-docs.md

Bullet point 3 did not start a new list item since a line break was missing.

doc/md: fixing a formatting error in writing-docs documentation

---

doc/md/writing-docs.md

@a8m It is weird. Adding the missing space leads to the third bullet point still being inlined: 
Having the extra line break like I did before results in a new paragraph: 
Note the different spacings between 1 and 2 and 2 and 3. 
I am unsure. Is this the intended behaviour?

doc/md: adding mising space in writing-docs documentation

---

doc/website/blog/2021-07-29-generate-a-fully-working-go-crud-http-api-with-ent.md

This was feedbacked to me by a reader.

doc/website/blog: Fixes a typo in elk blog post.

---

doc/md/code-gen.md

Fixed a typo  that blocked the code from compiling

docs/md/codegen fix typo in EnsureStructTag example

---

doc/md/crud.md
doc/md/features.md

I found these while reading the documentation.

Fix typos in documentation

---

doc/md/getting-started.md

Change order in documentation to first create a go env' and then install ent.
This is meant to avoid having ent on your global pkgs.

moved setup go envirnoment before installation

---

CONTRIBUTING.md

If one would change a template in `entc/gen/template` and not run regenerate `go-bindata/bindata` contents, code generation would not take changes into account.

ent: Fixes error in CONTRIBUTING.md

---

dialect/sql/sqlgraph/graph.go
dialect/sql/sqlgraph/graph_test.go

For example, in PostgreSQL, every statement is executed within a transaction. Therefore, we can avoid creating transaction
blocks manually (group of statements surrounded by BEGIN and COMMIT) for `CreateNode` operations with a single SQL statement.
Benchmark (based on [@mattn reference](https://github.com/mattn/echo-ent-example/pull/2#issuecomment-894250707)) was improved from:
(2000 Inserts)   8.41s      4206748 ns/op    4595 B/op    115 allocs/op
To:
(2000 Inserts)   4.66s      2330222 ns/op    4107 B/op    104 allocs/op
---
[MySQL doc](https://dev.mysql.com/doc/refman/8.0/en/commit.html):
> By default, MySQL runs with autocommit mode enabled. This means that, when not otherwise inside a transaction, each statement is atomic, as if it were surrounded by START TRANSACTION and COMMIT. You …

dialect/sql/sqlgraph: avoid creating tx blocks for single statement create operation

---

doc/website/package.json
doc/website/yarn.lock

I have made some changes to the version of the transitive dependency in `doc/website`, due to security issues.
Here's a list of upgrades version of transitive dependency:
1. `glob-parent`
2. `browserslist`
3. `trim`
Please check it, if you have a time, Thanks!
cc @a8m

doc/website: upgrade several transitive depedency that have security problems

---

entc/integration/type_test.go

**Description**
I made some code changes to file `type_test.go`, changing from `Save` to `Exec` in the `Create` operation.
Please check it, if you have a time, Thanks!
cc @a8m

refactor(entc/integration): change `Save` to `Exec` in create operation

---

entc/integration/hooks/hooks_test.go
entc/integration/migrate/migrate_test.go

**Description**
I made some code changes to file `type_test.go`, changing from `Save` to `Exec` in the Create operation.
List of file that I'have changed:
1. `entc/integration/migrate/migrate_test.go`
2. `entc/integration/hooks/hooks_test.go`
Please check it, if you have a time, Thanks!
cc @a8m

refactor(entc/integration): change Save to Exec in create operation

---

dialect/gremlin/encoding/graphson/bench_test.go
dialect/sql/bench_test.go
entc/gen/bench_test.go

This allows a full picture when continuous benchmarking
is added to this repository and when any changes are made
to the code in here.
Fixes #1918
This allows for hassle-free continuous benchmarking for example per https://dashboard.github.orijtech.com/benchmark/1cd1d34215e044cda8e391a2daf7448a

all: add (*testing.B).ReportAllocs() to all benchmarks

---

dialect/sql/schema/mysql.go

Fixed #1945.
Screenshot from our integration tests environment.

dialect/sql/schema: revert #1547 for mariadb

---

dialect/sql/builder.go
dialect/sql/builder_test.go
dialect/sql/sqlgraph/graph_test.go

The second argument for COALESCE function is not a dynamic argument (always 0).

dialect/sql: use raw 0 in COALESCE function on Add calls

---

doc/website/package.json
doc/website/yarn.lock

I have made some changes to the version of the transitive dependency in `doc/website`, due to security issues.
Here's a list of upgraded version of transitive dependency:
1. set-value
2. immer
Please check it, if you have time, Thanks!
cc @a8m

doc/website: fix security concern transitive depedency in website docs

---

dialect/sql/schema/mysql.go

Signed-off-by: storyicon <yuanchao@bilibili.com>
When using the `mediumtext` type of MySQL, the following problems occur:
```
sql/schema: mysql: unknown column type "mediumtext" for version "5.7.31-log"
```
This PR is intended to fix this problem.

feat(dialect): support mediumtext

---

entc/gen/type.go
entc/integration/ent/entql.go
entc/integration/ent/migrate/schema.go
entc/integration/ent/mutation.go
entc/integration/ent/schema/user.go
entc/integration/ent/user.go
entc/integration/ent/user/user.go
entc/integration/ent/user/where.go
entc/integration/ent/user_create.go
entc/integration/ent/user_update.go
entc/integration/gremlin/ent/mutation.go
entc/integration/gremlin/ent/user.go
entc/integration/gremlin/ent/user/user.go
entc/integration/gremlin/ent/user/where.go
entc/integration/gremlin/ent/user_create.go
entc/integration/gremlin/ent/user_update.go

Enum identifier needs to be formatted even if it's started with an upper-case letter.  
Fixed https://github.com/ent/ent/issues/1961

entc/gen: fix bug with enum separators

---

doc/website/blog/2021-07-29-generate-a-fully-working-go-crud-http-api-with-ent.md

I guess that the API have changed. When I run the current example I get:
```
$ go generate .
go: finding module for package github.com/masseelch/elk
go: downloading github.com/masseelch/elk v0.4.8
go: downloading entgo.io/ent v0.9.2-0.20210822190728-d84ac191b1c7
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/stoewer/go-strcase v1.2.0
2021/10/04 21:35:46 creating elk extension: no generator enabled: enable one by providing either "GenerateSpec()" or "GenerateHandlers()" to "NewExtension()"
exit status 1
be/ent/generate.go:4: running "go": exit status 1
```

update elk doc

---

doc/md/transactions.md

This addresses #2102 by highlighting `Unwrap` which must be used on a committed transaction if querying edges is done afterwards.

docs: mention Unwrap in Transaction docs

---

doc/md/tutorial-grpc-service-generation-options.md
doc/website/sidebars.js

Updating ent site documentation for changes to gRPC service method generation caused by https://github.com/ent/contrib/pull/158

Update gRPC Documentation for Service Method Generation Options

---

doc/md/tutorial-grpc-service-generation-options.md

Highlighting needs updating due to commit 2e3aca1

doc/md: fix highlighting in tutorial-grpc-service-generation-options.md

---

doc/website/docusaurus.config.js

Looks like loading the script from GH pages may be slow at times.  
cdnjs should be the right tool for the task.  
If this doesn't help, consider adding `async: true` (see [docs](https://docusaurus.io/docs/api/docusaurus-config#scripts))

ent/doc: load github buttons from cdnjs

---

doc/website/docusaurus.config.js

There used to be a footer which used this script  https://github.com/ent/ent/commit/0ed36ba188b7a1d86781151f74726e77a4996e34#diff-477f5f899cf264176483a09cd8fe61787411f3b03fb1d8eb75beae4798efafe1R20
but it was deprecated on https://github.com/ent/ent/commit/d9faf21e05acbd638088459fc45792d4e5fe6176

doc/website: remove deprecated script

---

README.md
README_jp.md
README_zh.md
doc/md/code-gen.md
doc/md/getting-started.md
doc/md/tutorial-setup.md

https://golang.org/doc/go-get-install-deprecation
```console 
$ go get entgo.io/ent/cmd/ent
go get: installing executables with 'go get' in module mode is deprecated.
To adjust and download dependencies of the current module, use 'go get -d'.
To install using requirements of the current module, use 'go install'.
To install ignoring the current module, use 'go install' with a version,
like 'go install example.com/cmd@latest'.
For more information, see https://golang.org/doc/go-get-install-deprecation
or run 'go help get' or 'go help install'
```

docs: use go get -d for installation

---

dialect/sql/schema/inspect_test.go
dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go

Right now if we define in postgres field with max character varchar custom type
```
field.String("name", json.RawMessage{}).
SchemaType(map[string]string{
dialect.Postgres: "varchar(100)",
}),
```
then first migration works as expected.
However the second time, migration operates and column already exists in the database, the migration fails with the following error:
```
sql/schema: creating changeset for \"my_table\": changing column type for \"name\" is invalid (varchar(100) != varchar):
```
This PR fixes the issue

Fix migrating Postgres fields with max character varchar custom type

---

doc/website/docusaurus.config.js

To make the Ent blog consumable by Rss / Feed Readers, applying the `feedOptions` configuration to the blog.
See [docs](https://docusaurus.io/docs/blog#feed)

doc/website: generate atom/rss feeds from the blog

---

dialect/sql/schema/migrate.go
dialect/sql/schema/mysql.go

PKs are indexes and therefore, the order does matter.
Thanks to ariga.io/atlas we found this issue.

dialect/sql/schema: do not sort primary-key columns before diff

---

dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go

Fix #2244
8.5. Date/Time Types
https://www.postgresql.org/docs/14/datatype-datetime.html

dialect/sql/schema: support `time with time zone` and `time without time zone`

---

cmd/ent/ent_test.go
cmd/internal/base/base.go

Previously if you ran `ent init` it would overwrite an existing file  f that already existed. Now  checks if that file already exists, and returns an error if so.

Add check that model file doesn't already exist on ent init

---

doc/md/aggregate.md

This PR adds an example on how to have  `HAVING + GROUP BY ` clause using ent.

Add docs for HAVING + GROUP BY clause

---

dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go

Fixes #2339 
Adds support for Postgres geometric types 
https://www.postgresql.org/docs/14/datatype-geometric.html

dialect/sql/schema: support postgres geometric types.

---

dialect/entsql/annotation.go
dialect/sql/schema/mysql.go
dialect/sql/schema/postgres.go
entc/gen/template/migrate/schema.tmpl
entc/integration/migrate/entv2/migrate/schema.go
entc/integration/migrate/entv2/schema/user.go
entc/integration/migrate/migrate_test.go

In future PRs, we can add support for `Search` predicates to simplify constructing the WHERE expression manually. Also, we should consider add the common index types to entsql:
```go
entsql.FullText()
entgql.GIN()
...
```

dialect/entsql: add support for index-type annotation 

---

CONTRIBUTING.md

Ent tests require the `json1` build flag to enable JSON support in SQLite, otherwise the tests fail with an error:
~~~
--- FAIL: TestSQLite (0.00s)
json_test.go:232:
Error Trace:	json_test.go:232
json_test.go:130
Error:      	Received unexpected error:
no such function: JSON_EXTRACT
Test:       	TestSQLite
FAIL
~~~
Let's make it easy on first-time contributors by prompting them to use this flag in the contributing documentation.

Add required json1 build tag to contributing instructions.

---

dialect/sql/schema/atlas.go
dialect/sql/schema/migrate.go

Currently, `golang-migrate` will not be able to scan versioned migration files generated because the filename does not match this pattern: [^([0-9]+)_(.*)\.(down|up)\.(. *)$](https://github.com/golang-migrate/migrate/blob/57aead3125fa6354d48199ac37f5bca5293ee600/source/parse.go#L21). So to satisfy the above pattern, we need to add names for the versioned migration files.
Another thing is that we should not execute `Planner.WritePlan` if there are no changes. Otherwise, it will generate empty migration files.

dialect/sql/schema: add name to versioned migration files

---

dialect/sql/schema/migrate.go
schema/field/field.go
schema/field/field_test.go
schema/field/type.go

Also, add both (T) and (*T) methods for RType

schema/field: expose RType.Implements method

---

dialect/sql/schema/migrate.go
dialect/sql/schema/migrate_test.go
go.mod
go.sum

This PR pulls in the latest atlas and disables its sumfile check. This will be introduced to Ent as an option later.

dialect/sql/schema: upgrade atlas and disable sum file creation

---

dialect/sql/schema/atlas.go
dialect/sql/schema/migrate_test.go
go.mod
go.sum

This adds the support for disabling FK when running with Atlas migrations
As I see I will need to add mocks for Atlas SQL calls if I want to add tests. I can do it if needed, or maybe there is another way to add the tests?

dialect/sql: without foreign keys option for atlas

---

doc/md/schema-def.md

The exemple incorrectly adds an ignored `User.Index` method, although ent actually needs a `User.Indexes` method as part of `ent.Interface`

Update schema-def to use proper method

---

doc/md/versioned-migrations.md

SSIA
Related to this issue #2408.

Write a document for custom formatter of migrate

---

dialect/sql/schema/sqlite.go
entc/integration/migrate/entv2/car.go
entc/integration/migrate/entv2/car/car.go
entc/integration/migrate/entv2/car/where.go
entc/integration/migrate/entv2/car_create.go
entc/integration/migrate/entv2/car_query.go
entc/integration/migrate/entv2/car_update.go
entc/integration/migrate/entv2/migrate/schema.go
entc/integration/migrate/entv2/mutation.go
entc/integration/migrate/entv2/pet.go
entc/integration/migrate/entv2/pet/pet.go
entc/integration/migrate/entv2/pet/where.go
entc/integration/migrate/entv2/pet_create.go
entc/integration/migrate/entv2/pet_query.go
entc/integration/migrate/entv2/pet_update.go
entc/integration/migrate/entv2/schema/user.go

Fixed https://github.com/ent/ent/issues/2421

dialect/sql/schema: prefix sqlite unique indexes with table name

---

doc/website/blog/2022-02-15-generate-rest-crud-with-ent-and-ogen.md

Generator example is importing `github.com/ariga/ogent` instead of `ariga.io/ogent`

update example import

---

schema/field/internal/numeric.tmpl
schema/field/numeric.go

All examples used repeated argument names, which do not compile

Fix incorrect Go code in GoType() doc comments

---

dialect/sql/schema/migrate.go

What's the problem: Under versioned migration on MySQL 8.0, unique string field would be generated as type varchar(191) instead of varchar(255). This is because in generating migration files by NamedDiff(), sqlDialect's init() method is not called. 
Further concern: For init() function, MySQL and Postgres's implementation checks the database version which is what I want. But SQLite's implementation checks the foreign_keys support. So I think there might be a better may to check the database version before doing Diff().

init db version before executing diff

---

doc/md/tutorial-todo-gql-filter-input.md

A few points:
- I could not think of a better example for the custom filter, I wanted to use a where filter for a field present in the page, so this limited me to `createdAt` and `status`.
- Dependencies of https://github.com/a8m/ent-graphql-example should be updated to make it work.
- I linked the `Templates` and `SchemaHooks` with docs for the `@master` version, but we should change it to a permanent version.

doc/md: document custom where filters

---

dialect/sql/builder.go
dialect/sql/builder_test.go
entc/integration/integration_test.go

This PR adds a few example of the sub-query usage, I could not think a better example for the join case.
Related: https://github.com/ent/ent/issues/2484#issuecomment-1108492471
I have changed the `builder.go` as well otherwise a empty `FROM` is always generated:

Sub queries

---

entql/internal/types.tmpl
entql/types.go

This feature allow me to write code shorter than current implement. Support `entql.FieldNil` and `entql.FieldNotNil`
```diff
-type timeNil struct {
-	entql.TimeP
-}
-func (p *timeNil) Field(name string) entql.P {
-	return entql.FieldNil(name)
-}
-		tf.WhereDeleteTime(&timeNil{})
+		tf.WhereDeleteTime(entql.TimeFunc(entql.FieldNil))
```

feat: add Nil/NotNil predicates

---

dialect/sql/schema/atlas.go
dialect/sql/schema/atlas_test.go
dialect/sql/schema/migrate.go
dialect/sql/schema/migrate_test.go
dialect/sql/schema/mysql.go
dialect/sql/schema/postgres.go
dialect/sql/schema/sqlite.go
doc/md/migrate.md
doc/md/versioned-migrations.md
entc/integration/migrate/migrate_test.go
entc/integration/migrate/versioned/group.go
go.mod
go.sum

This PR adds support for a file based type storage when using versioned migrations. The file called `.ent_types` is written to the migration directory alongside the migration files and will be kept in sync for every migration file generation run.
In order to not break existing code, where the type storage might differ for different deployment, global unique ID mut be enabled by using a new option. This will also be raised as an error to the user when attempting to use versioned migrations and global unique ID.
Documentation will be added to this PR once feedback on the code is gathered.
Fixes #2587 
----- 
I have discussed with Ariel already, that we will move the configuration for allocated pk ranges to the schema level. We haven't yet figured out, how to do this best, but it will come.

dialect/sql/schema: file based type store

---

doc/md/tutorial-todo-crud.md

Fixed a typo in the tutorial-todo-crud.

doc/tutorial: fix typos in tutorial-todo-crud

---

dialect/sql/schema/migrate.go
dialect/sql/schema/migrate_test.go

Keep the same API as schema.Create

dialect/sql/schema: setup tables before running migrate diff

---

dialect/sql/schema/schema.go
entc/gen/graph.go
entc/integration/edgeschema/ent/client.go
entc/integration/edgeschema/ent/migrate/schema.go
entc/integration/edgeschema/ent/mutation.go
entc/integration/edgeschema/ent/schema/tweetlike.go
entc/integration/edgeschema/ent/tweetlike.go
entc/integration/edgeschema/ent/tweetlike/tweetlike.go
entc/integration/edgeschema/ent/tweetlike/where.go
entc/integration/edgeschema/ent/tweetlike_create.go
entc/integration/edgeschema/ent/tweetlike_query.go
entc/integration/edgeschema/ent/tweetlike_update.go

This PR allows defining edge schemas with any order of their edges, but still, enforces the ordering of the fields in the ID annotation
cc @Liooo

entc/gen: ignore edge-fields order in edge-schema with composite identifiers 

---

doc/md/tutorial-todo-crud.md

When run 'go generate ./ent', got error on [create type Todo: invalid default value for enum field "status"]
Because todo.graphql on tutorial-todo-gql.md says enum Status is "IN_PROGRESS"

doc/md: fixing enum Status in Add Fields To The Schema

---

entc/gen/type.go
entc/integration/ent/fieldtype/fieldtype.go
entc/integration/ent/migrate/schema.go
entc/integration/ent/role/role.go
entc/integration/gremlin/ent/fieldtype/fieldtype.go

Fixes https://github.com/ent/ent/issues/2756

entc/gen: skip enum identifier checks in case it has custom Go type

---

dialect/sql/builder.go
dialect/sql/builder_test.go
go.sum

This is basically the identical change to #2735, but for NotIn(). Also added tests for both cases.
This bug currently prevents anyone using NotIn() from upgrading from v0.10.x to v0.11.x.

dialect/sql/builder: make sql.NotIn() with empty args fallback to NOT FALSE

---

doc/md/predicates.md

An invalide sql statement is provider in documentation, just a missing `)`

docs: Correct expression on documentation

---

entc/gen/template/dialect/sql/feature/upsert.tmpl
entc/integration/customid/ent/account_create.go
entc/integration/customid/ent/blob_create.go
entc/integration/customid/ent/car_create.go
entc/integration/customid/ent/device_create.go
entc/integration/customid/ent/doc_create.go
entc/integration/customid/ent/group_create.go
entc/integration/customid/ent/intsid_create.go
entc/integration/customid/ent/mixinid_create.go
entc/integration/customid/ent/note_create.go
entc/integration/customid/ent/other_create.go
entc/integration/customid/ent/pet_create.go
entc/integration/customid/ent/revision_create.go
entc/integration/customid/ent/session_create.go
entc/integration/customid/ent/token_create.go
entc/integration/customid/ent/user_create.go
entc/integration/edgeschema/ent/tweettag_create.go
entc/integration/ent/item_create.go
entc/integration/ent/license_create.go

Fixed https://github.com/ent/ent/issues/2000
After https://github.com/ent/ent/pull/2011 immutable fields are still being ignored in case of bulk upsert. Example of generated code before fix:
```go
func (u *MyEntityUpsertBulk) UpdateNewValues() *MyEntityUpsertBulk {
u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
for _, b := range u.create.builders {
if _, exists := b.mutation.ID(); exists {
s.SetIgnore(myentity.FieldID)
return // <-- if id exists, we will never call SetIgnore for created_at and created_by
}
if _, exists := b.mutation.CreatedAt(); exists {
s.SetIgnore(myentity.FieldCreatedAt)
}
if _, exists := b.mutation.CreatedBy(); exists {
s.SetIgnore(myentity.FieldCreatedBy) …
```

entc/gen: fix immutable fields updating during bulk upsert

---

dialect/sql/builder.go
dialect/sql/builder_test.go
entc/integration/integration_test.go

Hello 👋, `EqualFold` currently does not escape the argument, this can lead to problems, like returning multiple results when the first/last character of the argument is `%` and `pq: LIKE pattern must not end with escape character` when the first/last  character of the argument is a escape character.
While at it, I revised the points raised on #1484 (from the Postgres point of view). There seems to be a lot of different information about the use of `ILIKE` vs `LOWER` and I could not reach a conclusion.
I think we just leave as is but we should keep in mind that may exists a faster way available, when we have a user that needs it, we could look at it again.
- https://stackoverflow.com/a/41691993
- https://dba.stackexchange.com/questions/89901/lower-vs-ilike-on-postgresql
- …

dialect/sql: escape EqualFold on Postgres

---

doc/md/tutorial-todo-gql.mdx

I was getting the error below following gql tutorial, had to update package name from ent -> todo
```
validation failed: packages.Load: -: found packages todo (ent.resolvers.go) and ent (generate.go) in /home/broody/development/go_tutorial/ent-graphql-example
/home/broody/development/go_tutorial/ent-graphql-example/generate.go:1:1: package ent; expected todo
exit status 1
generate.go:4: running "go": exit status 1
```

doc/md: fix package name breaking generate

---

dialect/sql/schema/atlas.go
dialect/sql/schema/migrate_test.go

Not entirely sure yet we have to add some code to handle BC. @a8m Your thoughts?
For existing projects, it will no longer allocate a range in the types table. Since the join table never used any autoincrement, there is no information lost. 
I am not sure thought, if I oversee something here. The range will stay allocated for existing projects and we cannot remove the allocation since this would result incorrect ranges for every type with a range suceeding the one allocated for any join table.

dialect/sql/schema: no longer allocate a PK range for a join table

---

doc/md/tutorial-todo-gql-node.md

Please take a look. This fixes the mutation query to match the todo.graphql file. It also removes a section in the gqlgen.yml that doesn't appear during the tutorial.
Curiously, the diff section in the gqlgen.yml file is already present, so I am not entirely sure what should be happening there.

doc: make mutation and variable match todo.graphql

---

doc/md/tutorial-todo-gql-field-collection.md
doc/md/tutorial-todo-gql-filter-input.md
doc/md/tutorial-todo-gql-mutation-input.md
doc/md/tutorial-todo-gql-node.md
doc/md/tutorial-todo-gql-paginate.md
doc/md/tutorial-todo-gql-schema-generator.md
doc/md/tutorial-todo-gql-tx-mutation.md

one of the examples.
https://entgo.io/docs/tutorial-todo-gql-field-collection
link to "GraphQL example".

doc/md: broken link to "GraphQL example"

---

entc/gen/template/builder/setter.tmpl
entc/gen/template/builder/update.tmpl
entc/gen/template/dialect/sql/update.tmpl

Close: https://github.com/ent/ent/issues/2938

entc: remove space around `continue` for 1.18 compatible 

---

doc/md/tutorial-todo-gql-filter-input.md
doc/md/tutorial-todo-gql-mutation-input.md
doc/md/tutorial-todo-gql-tx-mutation.md

This is a collection of fixes that look like are needed. I have some doubts because some fixes here are added in later pages (notable example being the addition of `entgql.WithSchemaGenerator()` to entc.go in doc/md/tutorial-todo-gql-filter-input.md, which is required to make entc.go successfulliy complete, but which is added in the tutorial in a later page, https://entgo.io/docs/tutorial-todo-gql-schema-generator — though there are others that I've found). My suspicion is that the page order has changed over the construction of the tutorial.
Please take a look.

docs/md: various fixes

---

dialect/sql/schema/atlas.go
dialect/sql/schema/migrate.go
dialect/sql/schema/mysql.go
dialect/sql/schema/mysql_test.go
dialect/sql/schema/postgres.go
dialect/sql/schema/postgres_test.go
dialect/sql/schema/sqlite.go
dialect/sql/schema/sqlite_test.go
entc/integration/integration_test.go
entc/integration/migrate/migrate_test.go
go.mod
go.sum

dialect/sql/schema: disable foreign keys before opening a transaction

---

entc/entc.go
entc/gen/graph.go
entc/load/load.go
entc/load/load_test.go
entc/load/testdata/buildflags/group.go
entc/load/testdata/buildflags/user.go

This allows passing arbitrary build flags to the schema package loader,
which in turn can be used to pass build constraints affecting what
schema types and/or methods are visible.
As a particular use case, this should make it easier to implement
two-pass code generation to deal with circular imports in hooks (#892).

Add `BuildFlags` to schema loader configuration

---

dialect/sql/schema/atlas.go
dialect/sql/schema/migrate_test.go

I'm playing with [Timescale](https://www.timescale.com/), Timescale is a PostgreSQL extension that adds/improves support for time series data.
Timescale works by converting a normal table into a `hypertable`, it's not possible to use Timescale with Ent right now because the primary key of the ID field cause problems.
More info: 
- https://docs.timescale.com/timescaledb/latest/how-to-guides/schema-management/about-constraints/
- https://stackoverflow.com/a/68066535
One solution is avoiding creating the primary key in the first place, to do this on the user side of things a migration hook can be used:
```go
func WithoutPrimaryKey(tableName string) schema.MigrateOption {
return schema.WithHooks(func(next schema.Creator) schema.Creator {
return schema.CreateFunc(func(ctx context.Context, …
```

dialect/sql: avoid setting the primary key when no primary key is present

---

entc/gen/type.go
entc/gen/type_test.go

This fixes the code generator to make fields in an entity with the name `driver` to get generated as `_driver` to avoid a collision preventing compilation. 
1. `go run -mod=mod entgo.io/ent/cmd/ent init Test`
2. Add a field called `driver`
```
// Fields of the Test.
func (Test) Fields() []ent.Field {
return []ent.Field{
field.String("driver"),
}
}
```
3. `go generate`
Code wont compile because `<T>Mutation` expects to access `m.driver` which is originally contained from the embedded struct `<T>.config`

entc/gen: add driver as a reserved field word

---

dialect/sql/schema/writer.go
dialect/sql/schema/writer_test.go

I think a return is missing, since the case for `INSERT/UPDATE`  is delegated to `Exec`, but I'm not 100% sure.
Please review if this makes sense.
I think this fixes #3137, I have tested and the migration is generated as expected.
https://github.com/ent/ent/blob/d7f2f3a098633ae8c6f844ce707a2eb983b1a340/dialect/sql/sqlgraph/graph.go#L1500-L1507

dialect/sql/schema: fix issue with WriteDriver when using Postgres with Query

---

doc/md/tutorial-grpc-server-and-client.md

The documentation uses a deprecated function to setup a connection for an insecure gRPC call
Should be fixed with this PR

fix: Remove deprecated call in documentation

---

entc/gen/template/base.tmpl
entc/integration/ent/ent.go

Fixed https://github.com/ent/ent/issues/3208
Verified this with the following command:
```zsh
repeat 50 { go generate ./... && git --no-pager diff }
```

entc/gen: explicitly import node packages in generate ent.go file

---

entc/gen/template/runtime.tmpl

**Issue**
I have a mixin that includes both a policy and an interceptor. After running `go generate ./...`, `runtime.go` is invalid and includes a number of errors, namely `invalid argument: index 1 out of bounds [0:1]`. 
As discussed on [discord](https://discord.com/channels/885059418646003782/885059419107360779/1060990994243391528), this change fixes the above issue and ensures that interceptors are indexed starting at 0.

Do not increment idx for interceptors when a policy is present

---

doc/md/graphql.md

Hey,
a minor issue I noticed while browsing.

doc/md: fix broken link to Field Collection tutorial

---

dialect/sql/builder.go
dialect/sql/builder_test.go
dialect/sql/sqlgraph/graph.go
dialect/sql/sqlgraph/graph_test.go

Fixed https://github.com/ent/ent/issues/3221

dialect/sql/sqlgraph: ignore ORDER BY clauses in COUNT queries

---

entc/gen/template/builder/delete.tmpl
entc/gen/template/dialect/sql/update.tmpl

Fixed https://github.com/ent/ent/issues/3222. 
The ideal fix is to avoid these dynamic receiver names and use one letter for all: c for create, q for query, etc.

entc/gen: avoid codegen conflict with one letter (n) receivers

---

doc/md/dialects.md

This PR fixes two links in the [Dialects](https://entgo.io/docs/dialects/) doc page that are not working because they link to `#atlas-integration` in the current page (which doesn't exist), when they should actually link to `migrate.md#atlas-integration`:

doc/md: fix broken "Atlas migration engine" links on dialects.md

---

entc/load/load.go

This returns errors from both packages after Load() -> issues loading that can crop up by having a `go.work` file present are surfaced more clearly with this in place which improves user experience.

entc: Return errors from both packages

---

dialect/sql/builder.go
dialect/sql/builder_test.go

This PR improves the way we handle returning the `Table` for the `Selector`.
---
When handling complex queries, `Table()` will be called with a `*Selector`, causing a panic, this PR tries to solve this problem by checking the type and doing a recursive search for the first `SelectTable` found.
I'm not sure about the part were we use the first element, not sure if this is the correct behavior, but the test pass and things works.
We can improve code from:
```go
err = client.Debug().User.Query().Modify(func(s *sql.Selector) {
f := sql.P()
f.WriteString("calculate_score")
f.Wrap(func(b *sql.Builder) {
b.WriteString(s.C(user.FieldName)).Comma().WriteString("'" + searchString + "'") // <--- We improve this part
})
u := sql.Table(user.Table)
subquery := …
```

dialect/sql: improve support for subqueries

---

doc/md/features.md

privacy.md was renamed to privacy.mdx in commit f226627d6700.
When trying to click on one of the 'privacy' links on the features page you get the following error:
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>15DQ15S3VAEQA8PW</RequestId>
<HostId>
HxNShnveIK1dyPbqjFK/v7/x/VqKyysl4XWBPiEr75PgLkjl0CZjWN0PRzQcFMI0uZWPOpHS49Q=
</HostId>
</Error>

doc/md: fix broken privacy.md links

---

doc/md/versioned-migrations.mdx

add code that checks if the migration directory exists, and creates it otherwise

doc: add an instruction to create a migrations directory

---

dialect/sql/schema/atlas.go
dialect/sql/schema/migrate_test.go

Calling `StateReader.ReadState` should set up an Ent driver instead of panicking.

dialect/sql/schema: use the Atlas as state reader

---

cmd/internal/base/base.go

This enables the use of the [`gen.Funcs`](https://github.com/ent/ent/blob/master/entc/gen/func.go#L28) helper FuncMap in `ent new`.

ent: Attach Funcs for `ent new` templates

---

dialect/sql/builder.go
dialect/sql/sqlgraph/graph.go
dialect/sql/sqlgraph/graph_test.go
entc/integration/integration_test.go

In the next PRs, I plan to refactor a bit the `sqlgraph` package to remove code duplication. Then, work on exposing these capabilities in the fluent API.
cc @giautm

dialect/sql/sqlgraph: add function to order by edge terms

---

doc/md/getting-started.mdx
examples/start/start.go

Hi, thanks for maintaining this awesome repository.
I found some typo while I was doing hand-on tutorial in getting-started document. It's really trivial but I think it's good to fix this because many newbies are reading this document.

doc: Fix typo in tutorial

---

.github/workflows/ci.yml
cmd/ent/ent_test.go
cmd/entc/entc_test.go
cmd/internal/base/base.go
doc/md/code-gen.md

The --idtype flag predates the field.<Type>(id) option. See, https://entgo.io/docs/schema-fields\#id-field.

cmd/ent: hide the --idtype flag from generate command

---

doc/md/ci.mdx

The link for ent/contrib/ci is broken on https://entgo.io/docs/ci/ . So I fixed it.

doc/md/ci: fix broken link for ent/contrib/ci action's repo

---

dialect/sql/builder.go
dialect/sql/schema/atlas.go

By not relying on the SchemaDiff signature, we allow the schema.Differ to be extended without introducing breaking changes to ent

dialect/sql/schema: allow ariga.io/atlas schema diff to be extended

---

dialect/sql/sqljson/sqljson.go
dialect/sql/sqljson/sqljson_test.go
entc/integration/json/json_test.go

Some drivers like mysql encode them as 0/1

dialect/sql/sqljson: inline boolean values

---

entc/gen/template/meta.tmpl
entc/gen/template/runtime.tmpl
entc/gen/type.go
entc/integration/json/ent/migrate/schema.go
entc/integration/json/ent/mutation.go
entc/integration/json/ent/runtime.go
entc/integration/json/ent/schema/user.go
entc/integration/json/ent/user.go
entc/integration/json/ent/user/user.go
entc/integration/json/ent/user/where.go
entc/integration/json/ent/user_create.go
entc/integration/json/ent/user_update.go
entc/integration/json/json_test.go
schema/field/field.go
schema/field/field_test.go

This PR changes the way slice types are built and adds the possibility to add a custom validation function to json slice types.

schema/fields: validate for slices builder

---

doc/md/tutorial-todo-gql-paginate.md
doc/md/tutorial-todo-gql-schema-generator.md
doc/website/blog/2021-11-15-announcing-entoas.md

Fix from `Annotation()` to `Annotations()` as the correct edge.assocBuilder method name.

doc/md: fix edge.Annotations method name typo

---

doc/md/tutorial-setup.md

when running ent init the following is returned:
`Command "init" is deprecated, use "ent new" instead`

doc: fix new project instructions in tutorial-setup.md

---

dialect/sql/sqlgraph/errors.go

Adding these checks makes sure that when the error is nil these do not panic because of a nil pointer exception.
It is just a minor thing but something that bugged me when using these functions.
The ```IsConstraintError``` does not need it due to the use of ```errors.As``` which has these same checks.

Feat: added nil checks to sqlgraph constraint errors

---

doc/md/crud.mdx

we need to use the given pointer `c`  to update it instead of creating a new `ent.PetCreate`, right? 🙈

Fix example in docs/crud/#create-many

---

doc/md/dialects.md

SSIA
PostgreSQL v15 has been tested in CI so we can say that ent officially supports v15.
https://github.com/ent/ent/pull/3152

doc/md: drop v10 support and add v15 for PostgreSQL

---

doc/website/blog/2023-02-23-simple-cms-with-ent.mdx

I'm fixing a typo fix described in the #3836
Please check it out when you have some time. And thanks again for creating and maintaining this, hope to use this in the future and to follow up on helping in anything I can.

typo fix for the simple cms entry

---

dialect/sql/sqlgraph/graph.go

multi order may generate predicates, so running the order funcs first allows reusing aliases. 
If the predicates run first if there is a multiOrder field that generates it's own predicates, the predicates are unable to find the alias of the join and errors not finding the column on the table.
Related to: https://github.com/ent/contrib/pull/559

fix: swap the order of handling order and pred  in the graph select func

---

dialect/sql/sqlgraph/graph.go

Fixes #3829 
Use the same logic for row scanning between `*creator.insertLastID` and `batchCreator.insertLastIDs`.

dialect/sql/sqlgraph: fix scanning non-numeric IDs

---

dialect/sql/schema/atlas.go

sqlite fts5 virtual tables create additional tables that are automatically deleted when the virtual table is deleted.
This will cause "no such table" errors when trying to drop them when creating a new migration.

dialect/sql/schema: Atlas cleanSchema should handle non-existent tables

---

doc/md/code-gen.md
doc/md/data-migrations.mdx
doc/md/schema-annotations.md
doc/md/schema-def.md
doc/md/schema-indexes.md
doc/md/tutorial-todo-gql.mdx

When searching or reloading certain document pages, the website automatically adds a trailing slash, which causes some URL paths to break.
1. Access the [Ent docs](https://entgo.io/docs/getting-started).
2. Search for `Custom Table Schema`
3. Click on the `multi-schema doc`.
Using **file path** instead of **URL path** for link
ref: https://docusaurus.io/docs/markdown-features/links

doc/md: fix some broken links caused by trailing slash

---

doc/md/extension.md

- added [entrest](https://github.com/lrstanley/entrest) to the list.
- [entviz](https://github.com/hedwigz/entviz) is now deprecated, so I've marked it as such.
- I've moved both entviz and elk into their own section so it's more clear that they are deprecated.

docs: add entrest, mark entviz as deprecated, move deprecated into its own section

---

doc/md/transactions.md
entc/gen/template/ent.tmpl

Adds documentation to both generated code and the website noting that calling `someEntity.Unwrap()` on a non-transactional entity will cause a panic.
I wasn't 100% sure if the generated code needed to be included in this PR, but I left it out for now since it's easier to read. 
Please let me know if there's anything I'm missing here. Thank you!

doc: add warning for Unwrap

---

dialect/sql/builder.go
dialect/sql/builder_test.go
dialect/sql/sql.go
dialect/sql/sql_test.go

The `HasPrefix` and `HasSuffix` always generate `LIKE` operator which is case sensitive. In some of the operations, we want case insensitive operations instead and this PR adds methods to the sql package:
- `FieldHasPrefixFold`
- `FieldHasSuffixFold`
To support that, the underlying builder gets following methods:
- `HasPrefixFold`
- `HasPrefixFold` on `Predicate` type.
- `HasSuffixFold`
- `HasSuffixFold` on `Predicate` type.
FYI @a8m

HasPrefixFold and HasSuffixFold

---

dialect/sql/schema/atlas.go

before:
`Error: migration checks are available to logged-in users only. Use 'atlas login' to access this feature: %!w(<nil>)`
after:
`Error: migration checks are available to logged-in users only. Use 'atlas login' to access this feature`

dialect/sql: fix error formatting 

---

doc/md/code-gen.md
doc/md/tutorial-setup.md

As pointed [here](https://go.dev/doc/go-get-install-deprecation), since Go 1.18, `go get` always act as `go get -d`.

doc: remove `-d` flag in `go get` commands

---

entc/load/schema_test.go
schema/field/field_test.go
schema/field/internal/numeric.tmpl
schema/field/numeric.go

Add `DefaultFunc` and `UpdateDefault` to Float type to address [this issue](https://github.com/ent/ent/issues/4247).
Looking forward to feedback and any suggestions.

Add `DefaultFunc` and `UpdateDefault` to Float type

---

entc/gen/template/privacy/privacy.tmpl

Fixes issue #4193 by skipping generation of privacy adapter for mutations when the node is a view.

fix: privacy.go invalid when schema has view

---

entc/gen/template/dialect/sql/entql.tmpl

Essentially an identical bug as fixed in #4273 (cc @a8m)

Fix: entql.go invalid when schema has View

---

entc/gen/template.go
entc/gen/template/builder/mutation.tmpl

I am building an extension that can Add MediaPicker support to any Model via Annotation and integration with GraphQL.
So this extension will automatically generate the additional types for Mutation and generate the graphql types and bind them with `type xxMutation {}`
```go
func (Post) Annotations() []schema.Annotation {
return []schema.Annotation{
entsaasmedia.MediaFields(entsaasmedia.FieldOption{Name: "featured"}, entsaasmedia.FieldOption{Name: "icon"})
}
}
```
So we need a way to customize the mutation type to add additional fields without copying the whole `mutation.tmpl` file in custom templates directory and then override

ability to add additional fiels to type xxMutation {}

---

entc/gen/type.go

I created a new object called `Schema` for a project I was working on and was surprised that things weren't how i expected it.   
* The `schema` directory was updated and the `schema/schema.go` was overwritten.  
* There was a confiicdt with the `Client.Schema` migration pointer.  
Overall it seems bad to try to use `Schema` as an object name so this adds it to the list of Global indentifiers.  Both `schema` and `Schema` are both bad (for packages and objects) but just the uppercate `Schema` should cover both and provide a better error message?
```
go run ./cmd/entc new Schema
ent/new: new schema Schema: schema name conflicts with ent predeclared identifier "Schema"
exit status 1
```

Add 'Schema' to the restricted global identifiers

---

dialect/entsql/annotation.go
dialect/sql/schema/atlas.go
dialect/sql/schema/migrate_test.go
entc/gen/type.go

Preparation to rewrite the universal id feature to rely on type ranges defined statically in the schema instead of dynamically in a database.

dialect/entsql: allow to define auto increment start value

---

dialect/sql/schema/atlas.go

currently this error is returned: `sql/schema: sql/schema: universal id and increment start annotation are mutually exclusive`. This PR removes the double package prefix.

dialect/sql/schema: remove package prefix from globalid error

---

dialect/sql/schema/postgres.go

I could not store the max values of `uint32` using the default schema types.
To me it seems that the mapping is incorrect:
https://github.com/ent/ent/blob/b91f8daf0e3267a1c7818f8120e83a36d56054b3/dialect/sql/schema/postgres.go#L117-L118
`integer` type in PG ranges from `-2147483648 to +2147483647` (https://www.postgresql.org/docs/current/datatype-numeric.html) - which is not sufficient.
I then checked the other types and think that `uint16` also needs to be fixed.

fix: use bigint for uint32 and uint16 in postgres driver

---

entc/entc.go
entc/gen/globalid.go
entc/gen/globalid_test.go

If there is no conflict in the schema, the existing logic will not attempt to resolve a conflict. Therefore, if there is a conflict on file load, there now also is an attempt to fix the conflict.

entc/gen: resolve merge conflicts on file load

---

dialect/sql/schema/schema.go

fixes https://github.com/ent/ent/issues/4337

fix #4337: `ent schema` panics if any field contains the `DefaultExprs` annotation

---

cmd/entfix/entfix.go

different quote characters are used by different dialects

fix: set the dialect for the generated query

---

dialect/sql/schema/atlas.go
dialect/sql/schema/schema_test.go

While this change is correct and eventually should land, currently it is creating too many noise in existing projects. Therefore, this change is reverted until a better solution is found.
Closes https://github.com/ariga/atlas/issues/3437

dialect/sql/schema: revert min length logic for state reader

---

schema/field/field.go
schema/field/field_test.go

- **Issue**: The original `MaxLen` validator used `len(v)` (byte count), while databases like MySQL/PostgreSQL/SQLite define `varchar(size)` as **character count** (not bytes). This caused inconsistent validation for multi-byte characters (e.g., Chinese, Emoji).
- **Fix**: Switched to `utf8.RuneCountInString(v)` to count Unicode characters, ensuring the validation aligns with database constraints.
- **Impact**: All supported databases (MySQL/PostgreSQL/SQLite) now have consistent character-length checks at both application and database layers.
- **Future Compatibility**:
- For Oracle/SQL Server (where `varchar` uses byte counts by default), explicit syntax like `varchar(N CHAR)` or `nvarchar` can enforce character limits. This change does not affect existing logic but should be noted for …

schema/field: validate rune length with `MinRuneLen` / `MaxRuneLen`

---

dialect/sql/sqlgraph/errors.go
dialect/sql/sqlgraph/graph_test.go

- Issue: Currently, entc does not support verifying Check constraint violations
- Implementation: Add the new function `IsCheckConstraintError` to check the returned error message.

dialect/sql/sqlgraph: report check constraint violation with `IsCheckConstraintError`
